import { create } from 'zustand';
import * as SecureStore from 'expo-secure-store';

export type Language = 'en' | 'fr' | 'rn'; // rn for Kirundi (Rundi)

interface LanguageState {
  language: Language;
  setLanguage: (lang: Language) => Promise<void>;
  loadLanguage: () => Promise<void>;
}

export const useLanguageStore = create<LanguageState>((set) => ({
  language: 'en',
  setLanguage: async (lang: Language) => {
    await SecureStore.setItemAsync('user_language', lang);
    set({ language: lang });
  },
  loadLanguage: async () => {
    const lang = await SecureStore.getItemAsync('user_language');
    if (lang) {
      set({ language: lang as Language });
    }
  },
}));

export const translations = {
  en: {
    settings: "Settings",
    logout: "Logout",
    confirmLogout: "Confirm Logout",
    logoutMessage: "Are you sure you want to log out?",
    cancel: "Cancel",
    language: "Language",
    dataCountry: "Data Country",
    home: "Home",
    cart: "Cart",
    profile: "Profile",
    "murahawe ikaze kwa Dr. Gahungu:": "Welcome to Dr. Gahungu",
    doctors: "Doctors",
    pharmacies: "Pharmacies",
    hospitals: "Hospitals",
    insurances: "Insurances",
    explore: "Explore",
    categories: "Categories",
    "all categories": "All Categories",
    "deals of the day": "Deals of the day",
    "recommended for you": "Recommended for you",
    "featured pharmacies": "Featured Pharmacies",
    "featured hospitals": "Featured Hospitals",
    "featured insurances": "Featured Insurances",
    "featured doctors":"Featured Doctors",
    "Medecines for": "Medecines for",
    "no hospitals available": "No hospitals available",
    "no products available": "No products available",
     "no doctors available": "No doctors available",
    "no insurances available": "No insurances available",
    "no pharmacies available": "No pharmacies available",
    "no deals available": "No deals available",
    "product details": "Product Details",
    "add to cart": "Add to Cart",
    "added to cart": "Added to Cart",
    "go to cart": "Go to Cart",
    "out of stock": "Out of Stock",
    "available at": "Available at",
    locations: "Locations",
    contact: "Contact",
    price: "Price",
    "view on the map": "View on the map",
    "opening hours": "Opening hours",
    reviews: "Reviews",
    "no reviews yet": "No reviews yet",
    "write a review": "Write a review",
    submit: "Submit",
    "your review": "Your review",
    "thank you for your review": "Thank you for your review",
    "review submitted": "Review submitted",
    "review submission failed": "Review submission failed",
    "edit review": "Edit Review",
    "delete review": "Delete Review",
    mon: "MON",
    tue: "TUE",
    wed: "WED",
    thu: "THU",
    fri: "FRI",
    sat: "SAT",
    sun: "SUN",
    "accepted insurances": "Accepted Insurances",
    "insurance details": "Insurance Details",
    coverage: "Coverage",
    "contact details": "Contact Details",
    "pharmacy details": "Pharmacy Details",
    "hospital details": "Hospital Details",
    "service summary": "Service Summary",
    "admission process": "Admission Process",
    "available services": "Available Services",
    "available blood types": "Available Blood Types",
    "medical equipment": "Medical Equipment",
    "Partner Pharmacies": "Partner Pharmacies",
    "main location": "Main Location",
    "open in google maps": "Open in Google Maps",
    "doctor profile": "Doctor Profile",
    about: "About",
    "working hours": "Working Hours",
    "availability & booking": "Availability & Booking",
    "book an appointment": "Book an appointment",
    "appointment booked": "Appointment booked",
    "appointment booking failed": "Appointment booking failed",
    "see details": "See details",
    "insurance type": "Insurance Type",
    "coverage summary": "Coverage Summary",
    "claim process": "Claim Process",
    "partner hospitals": "Partner Hospitals",
    "partner pharmacies": "Partner Pharmacies",
    "office locations": "Office Locations",
    "branch office": "Branch Office",
    "all doctors": "All Doctors",
    "all pharmacies": "All Pharmacies",
    "all hospitals": "All Hospitals",
    "all insurances": "All Insurances",
    searchPlaceholder: "Search medicines, doctors, pharmacies...",
    searchPlaceholderText: "Search here with Gahungu Search...",
    "no results found for": "No results found for",
    "try different keywords": "Try different keywords",
    "searching for": "Searching for",
    "results for": "Results for",
    "recent searches": "Recent Searches",
    "clear all": "Clear All",
    "type to see suggestions": "Type at least 2 characters to see suggestions",
    "my prescriptions": "My Prescriptions",
    "covered by": "Covered by:",
    "no prescriptions found": "No results found for your prescriptions.",
    "try different spellings": "Try different spellings or fewer items.",
    payment: "Payment",
    "booking details": "Booking Details",
    doctor: "Doctor",
    date: "Date",
    time: "Time",
    type: "Type",
    online: "Online",
    "in-office": "In-Office",
    "consultation fee": "Consultation Fee(To be Fixed by Doctors)",
    "doctor service fee": "Doctor Service Fee",
    "total amount": "Total Amount",
    "payment method": "Payment Method",
    "pay with gahungu wallet": "Pay with Gahungu Wallet",
    "pay with gahungu card": "Pay with Gahungu Card",
    "my orders": "My Orders",
    "order hash": "Order #",
    "placed on": "Placed on:",
    total: "Total:",
    "check order status": "Check your order status",
    "no orders yet": "You have no orders yet.",
    "start shopping": "Start Shopping",
    "failed to load orders": "Failed to load orders. Please check your connection.",
    retry: "Retry",
    "update profile": "Update Profile",
    "full name": "Full Name",
    "whatsapp number": "WhatsApp Number (e.g., +257...)",
    updating: "Updating...",
    "save changes": "Save Changes",
    "failed to load profile": "Failed to load profile information.",
    "my bus tickets": "My Bus Tickets",
    new: "NEW",
    origin: "Origin",
    destination: "Destination",
    seat: "Seat",
    id: "ID:",
    "scan at boarding": "Scan at boarding",
    service: "Service",
    "no tickets yet": "You don't have any tickets yet.",
    "book a jk bus": "Book a JK BUS",
    "failed to load bus tickets": "Failed to load bus tickets. Please check your connection.",
    "select your seat": "Select Your Seat",
    available: "Available",
    reserved: "Reserved",
    selected: "Selected",
    vip: "VIP",
    "vip section": "VIP SECTION (1.5x Price)",
    "standard section": "STANDARD SECTION",
    "seats selected": "Seats Selected",
    "confirm booking": "Confirm Booking",
    "buses available": "Buses Available",
    "main terminal": "Main Terminal",
    "central station": "Central Station",
    "select seat": "Select Seat",
    "no buses found": "No buses found for this specific route on this date.",
    "try another route": "Try another route",
    "my transactions": "My Transactions",
    "total wallet activity": "Total Wallet Activity",
    "review spending": "Review your recent spending and top-ups",
    "total in": "Total In",
    "total out": "Total Out",
    "filter by month": "Filter by Month",
    "view all": "View All",
    "no transactions found": "No transactions found.",
    "failed to load transactions": "Failed to load transactions. Please check your connection.",
    "confirm payment": "Confirm Payment",
    "order summary": "Order Summary",
    subtotal: "Subtotal",
    "medicine service fee": "Medicine Service Fee",
    "paying with gahungu wallet": "Paying with Gahungu Wallet",
    "confirm and pay": "Confirm & Pay",
    "enter wallet pin": "Enter Wallet PIN",
    "enter pin message": "Please enter your 4-digit PIN to confirm payment.",
    "verify and pay": "Verify & Pay",
    "travel with comfort": "Travel with Comfort",
    "safe and reliable journeys": "Safe and reliable journeys across the region",
    "popular routes": "Popular Routes",
    from: "From",
    to: "To",
    "origin city": "Origin City",
    "destination city": "Destination City",
    "departure date": "Departure Date",
    "search buses": "Search Buses",
    "why choose jk bus": "Why choose JK BUS?",
    "air conditioned fleet": "• Air-conditioned modern fleet",
    "experienced drivers": "• Experienced and professional drivers",
    "realtime gps tracking": "• Real-time GPS tracking for safety",
    "change pin": "Change PIN",
    "create pin": "Create PIN",
    "verify current pin": "Verify Your Current PIN",
    "enter current pin message": "Please enter your current 4-digit PIN to proceed.",
    "current pin": "Current PIN",
    "verify pin": "Verify PIN",
    "set new pin": "Set Your New PIN",
    "update pin": "Update PIN",
    "set transaction pin": "Set Your Transaction PIN",
    "pin authorization message": "This 4-digit PIN will be used to authorize your payments.",
    "new pin": "New PIN (4 digits)",
    "confirm new pin": "Confirm New PIN",
    update: "Update",
    "save pin": "Save PIN",
    "app reviews": "App Reviews",
    "total reviews": "total reviews",
    "highly recommended": "Highly Recommended by Users",
    "trusted companion": "Trusted healthcare companion",
    "your name": "Your Name",
    "tap to rate": "Tap to Rate:",
    "gahungu team": "Gahungu Team",
    "failed to load reviews": "Failed to load reviews. Please check your connection.",
    "my engagement points": "My Engagement Points",
    "monetization goal": "Monetization Goal",
    threshold: "Threshold:",
    "points to reach goal": "EP to reach your goal! Keep it up! 💪",
    "goal reached": "Congratulations! You've reached your monetization goal! 🎉",
    "monetization info": "Note: After reaching {monetizationGoal.toLocaleString()} EP, you will be able to turn your points into money and withdraw it.",
    "daily summary": "Daily Summary",
    "posts liked today": "• Posts Liked Today:",
    "stories viewed today": "• Stories Viewed Today:",
    "points earned today": "• Points Earned Today:",
    "keep it up message": "Keep it up dear,our Team loves you!!",
    "secure access fee": "Secure Access Fee",
    "access fee message": "To ensure the best service, a small login access fee is required to continue.",
    "access fee": "Access Fee",
    "gahungu wallet": "Gahungu Wallet",
    "available balance": "Available Balance:",
    "default pin notice": "Notice: Your default wallet PIN is 1616. Please change it to continue.",
    "fee support message": "This fee supports the maintenance of Dr. Gahungu's pharmacy network and 24/7 availability.",
    "default pin warning": "Default PIN: 1616. Change it now!",
    "change pin to continue": "Change PIN to Continue",
    "pay and enter app": "Pay & Enter App",
    "retry connection": "Retry Connection",
    "wallet security": "Wallet Security",
    "enter pin to pay": "Enter PIN to authorize payment",
    "enter pin to show balance": "Enter PIN to show balance",
    "forgot pin": "Forgot PIN?",
    verify: "Verify",
    "contact admin": "Contact Admin",
    "contact admin whatsapp": "Would you like to open WhatsApp to contact the admin at +25777990118?",
    "my cart": "My Cart",
    "cart empty": "Your cart is empty!",
    "browse products": "BROWSE PRODUCTS",
    "choose payment method": "Choose Payment Method",
    "bank payment": "Bank Payment",
    "gahungu wallet balance": "Gahungu Wallet (Balance:",
    "proceed to payment": "Proceed to Payment",
    "failed to load wallet data": "Failed to load wallet data. Please check your connection.",
    ep: "EP",
    "link to website": "Link to the website",
    "click to whatsapp": "Click here to Whatsapp",
    "follow on instagram": "Follow them on Instagram",
    "follow on x": "Follow them on X",
    likes: "likes",
    "check out more here": "Check out more here",
    viewed: "Viewed",
    "ep eligible message": "Your current EP is {engagementPoints.toLocaleString()}, you are eligible to book.",
    "ep warning message": "Your current EP is less than {minEpRequired.toLocaleString()}.",
    "earn ep message": "Click here to increase your EP by watching stories, viewing posts and liking posts.",
    "customer support": "Customer Support",
    email: "Email",
    phone: "Phone",
    facebook: "Facebook",
    instagram: "Instagram",
    "terms and conditions": "Terms and Conditions",
    "last updated": "Last Updated: November 11, 2025",
    "terms introduction": "1. Introduction",
    "terms intro paragraph": "Welcome to GAHUNGU PHARMACY (\"App\", \"we\", \"us\", \"our\"). By downloading, accessing, or using our mobile application, you agree to be bound by these Terms and Conditions. If you do not agree, please do not use the App.",
    "terms medical disclaimer": "2. Medical Disclaimer",
    "terms medical disclaimer paragraph": "Always seek the advice of your physician or other qualified health provider with any questions you may have regarding a medical condition. Never disregard professional medical advice or delay in seeking it because of something you have read on this App. Reliance on any information provided by the App is solely at your own risk.",
    "terms user accounts": "3. User Accounts",
    "terms user accounts paragraph": "To access certain features, you must register for an account. You agree to provide accurate, current, and complete information during the registration process and to update such information to keep it accurate. You are responsible for safeguarding your password and for any activities or actions under your account.",
    "terms use of services": "4. Use of Services",
    "terms use of services paragraph": "You may use the App only for lawful purposes. You agree not to use the App to:\n- Purchase prescription medication without a valid prescription.\n- Violate any local, national, or international law.\n- Transmit any material that is defamatory, offensive, or otherwise objectionable.",
    "terms purchases and payments": "5. Purchases and Payments",
    "terms purchases and payments paragraph": "If you wish to purchase any product or service made available through the App, you may be asked to supply certain information relevant to your purchase. All payments made through the Gahungu Wallet are subject to the terms of our payment processing partners. We are not responsible for any errors or issues in the payment process.",
    "terms privacy": "6. Privacy",
    "terms privacy paragraph": "Your privacy is important to us. Our Privacy Policy explains how we collect, use, and share your personal information. By using this App, you agree to the collection and use of information in accordance with our Privacy Policy.",
    "terms limitation of liability": "7. Limitation of Liability",
    "terms limitation of liability paragraph": "In no event shall GAHUNGU PHARMACY, nor its directors, employees, partners, or agents, be liable for any indirect, incidental, special, consequential, or punitive damages, including without limitation, loss of profits, data, use, goodwill, or other intangible losses, resulting from your access to or use of or inability to access or use the App.",
    "terms changes to terms": "8. Changes to Terms",
    "terms changes to terms paragraph": "We reserve the right, at our sole discretion, to modify or replace these Terms at any time. We will provide notice of any changes by posting the new Terms and Conditions on this page.",
    "terms contact us": "9. Contact Us",
    "terms contact us paragraph": "If you have any questions about these Terms, please contact us at supportgahungupharmacy@gmail.com.",
  },
  fr: {
    settings: "Paramètres",
    logout: "Se déconnecter",
    confirmLogout: "Confirmer la déconnexion",
    logoutMessage: "Êtes-vous sûr de vouloir vous déconnecter ?",
    cancel: "Annuler",
    language: "Langue",
    dataCountry: "Pays des données",
    home: "Accueil", // Added missing key
    cart: "Panier", // Added missing key
    profile: "Profil", // Added missing key
    "murahawe ikaze kwa Dr. Gahungu:": "Bienvenue chez Dr. Gahungu",
    doctors: "Doctors",
    pharmacies: "Pharmacies",
    hospitals: "Hospitals",
    insurances: "Insurances",
    explore: "Explore",
    categories: "Categories",
    "all categories": "All Categories",
    "deals of the day": "Deals of the day",
    "recommended for you": "Recommended for you",
    "featured pharmacies": "Featured Pharmacies",
    "featured hospitals": "Featured Hospitals",
    "featured insurances": "Featured Insurances",
    "featured doctors":"Featured Doctors",
    "Medecines for": "Medecines for",
    "product details": "Product Details",
    "add to cart": "Add to Cart",
    "added to cart": "Added to Cart",
    "go to cart": "Go to Cart",
    "out of stock": "Out of Stock",
    "available at": "Available at",
    "no products available": "No products available",
     "no doctors available": "No doctors available",
    "no insurances available": "No insurances available",
    "no pharmacies available": "No pharmacies available",
    "no deals available": "No deals available",
    "no hospitals available": "No hospitals available",
    locations: "Locations",
    contact: "Contact",
    price: "Price",
    "view on the map": "View on the map",
    "opening hours": "Opening hours",
    reviews: "Reviews",
    "no reviews yet": "No reviews yet",
    "write a review": "Write a review",
    submit: "Submit",
    "your review": "Your review",
    "thank you for your review": "Thank you for your review",
    "review submitted": "Review submitted",
    "review submission failed": "Review submission failed",
    "edit review": "Edit Review",
    "delete review": "Delete Review",
    mon: "MON",
    tue: "TUE",
    wed: "WED",
    thu: "THU",
    fri: "FRI",
    sat: "SAT",
    sun: "SUN",
    "accepted insurances": "Accepted Insurances",
    "insurance details": "Insurance Details",
    coverage: "Coverage",
    "contact details": "Contact Details",
    "pharmacy details": "Pharmacy Details",
    "hospital details": "Hospital Details",
    "service summary": "Service Summary",
    "admission process": "Admission Process",
    "available services": "Available Services",
    "available blood types": "Available Blood Types",
    "medical equipment": "Medical Equipment",
    "Partner Pharmacies": "Partner Pharmacies",
    "main location": "Main Location",
    "open in google maps": "Open in Google Maps",
    "doctor profile": "Doctor Profile",
    about: "About",
    "working hours": "Working Hours",
    "availability & booking": "Availability & Booking",
    "book an appointment": "Book an appointment",
    "appointment booked": "Appointment booked",
    "appointment booking failed": "Appointment booking failed",
    "see details": "See details",
    "insurance type": "Insurance Type",
    "coverage summary": "Coverage Summary",
    "claim process": "Claim Process",
    "partner hospitals": "Partner Hospitals",
    "partner pharmacies": "Partner Pharmacies",
    "office locations": "Office Locations",
    "branch office": "Branch Office",
    "all doctors": "All Doctors",
    "all pharmacies": "All Pharmacies",
    "all hospitals": "All Hospitals",
    "all insurances": "All Insurances",
    searchPlaceholder: "Search medicines, doctors, pharmacies...",
    searchPlaceholderText: "Search here with Gahungu Search...",
    "no results found for": "No results found for",
    "try different keywords": "Try different keywords",
    "searching for": "Searching for",
    "results for": "Results for",
    "recent searches": "Recent Searches",
    "clear all": "Clear All",
    "type to see suggestions": "Type at least 2 characters to see suggestions",
    "my prescriptions": "My Prescriptions",
    "covered by": "Covered by:",
    "no prescriptions found": "No results found for your prescriptions.",
    "try different spellings": "Try different spellings or fewer items.",
    payment: "Payment",
    "booking details": "Booking Details",
    doctor: "Doctor",
    date: "Date",
    time: "Time",
    type: "Type",
    online: "En ligne",
    "in-office": "En cabinet",
    "consultation fee": "Consultation Fee(To be Fixed by Doctors)",
    "doctor service fee": "Doctor Service Fee",
    "total amount": "Total Amount",
    "payment method": "Payment Method",
    "pay with gahungu wallet": "Pay with Gahungu Wallet",
    "pay with gahungu card": "Pay with Gahungu Card",
    "my orders": "My Orders",
    "order hash": "Order #",
    "placed on": "Placed on:",
    total: "Total:",
    "check order status": "Check your order status",
    "no orders yet": "You have no orders yet.",
    "start shopping": "Start Shopping",
    "failed to load orders": "Failed to load orders. Please check your connection.",
    retry: "Retry",
    "update profile": "Update Profile",
    "full name": "Full Name",
    "whatsapp number": "WhatsApp Number (e.g., +257...)",
    updating: "Updating...",
    "save changes": "Save Changes",
    "failed to load profile": "Failed to load profile information.",
    "my bus tickets": "My Bus Tickets",
    new: "NEW",
    origin: "Origin",
    destination: "Destination",
    seat: "Seat",
    id: "ID:",
    "scan at boarding": "Scan at boarding",
    service: "Service",
    "no tickets yet": "You don't have any tickets yet.",
    "book a jk bus": "Book a JK BUS",
    "failed to load bus tickets": "Failed to load bus tickets. Please check your connection.",
    "select your seat": "Select Your Seat",
    available: "Available",
    reserved: "Reserved",
    selected: "Selected",
    vip: "VIP",
    "vip section": "VIP SECTION (1.5x Price)",
    "standard section": "STANDARD SECTION",
    "seats selected": "Seats Selected",
    "confirm booking": "Confirm Booking",
    "buses available": "Buses Available",
    "main terminal": "Main Terminal",
    "central station": "Central Station",
    "select seat": "Select Seat",
    "no buses found": "No buses found for this specific route on this date.",
    "try another route": "Try another route",
    "my transactions": "My Transactions",
    "total wallet activity": "Total Wallet Activity",
    "review spending": "Review your recent spending and top-ups",
    "total in": "Total In",
    "total out": "Total Out",
    "filter by month": "Filter by Month",
    "view all": "View All",
    "no transactions found": "No transactions found.",
    "failed to load transactions": "Failed to load transactions. Please check your connection.",
    "confirm payment": "Confirm Payment",
    "order summary": "Order Summary",
    subtotal: "Subtotal",
    "medicine service fee": "Medicine Service Fee",
    "paying with gahungu wallet": "Paying with Gahungu Wallet",
    "confirm and pay": "Confirm & Pay",
    "enter wallet pin": "Enter Wallet PIN",
    "enter pin message": "Please enter your 4-digit PIN to confirm payment.",
    "verify and pay": "Verify & Pay",
    "travel with comfort": "Travel with Comfort",
    "safe and reliable journeys": "Safe and reliable journeys across the region",
    "popular routes": "Popular Routes",
    from: "From",
    to: "To",
    "origin city": "Origin City",
    "destination city": "Destination City",
    "departure date": "Departure Date",
    "search buses": "Search Buses",
    "why choose jk bus": "Why choose JK BUS?",
    "air conditioned fleet": "• Air-conditioned modern fleet",
    "experienced drivers": "• Experienced and professional drivers",
    "realtime gps tracking": "• Real-time GPS tracking for safety",
    "change pin": "Change PIN",
    "create pin": "Create PIN",
    "verify current pin": "Verify Your Current PIN",
    "enter current pin message": "Please enter your current 4-digit PIN to proceed.",
    "current pin": "Current PIN",
    "verify pin": "Verify PIN",
    "set new pin": "Set Your New PIN",
    "set transaction pin": "Set Your Transaction PIN",
    "pin authorization message": "This 4-digit PIN will be used to authorize your payments.",
    "new pin": "New PIN (4 digits)",
    "confirm new pin": "Confirm New PIN",
    update: "Update",
    "save pin": "Save PIN",
    "app reviews": "App Reviews",
    "total reviews": "total reviews",
    "highly recommended": "Highly Recommended by Users",
    "trusted companion": "Trusted healthcare companion",
    "your name": "Your Name",
    "tap to rate": "Tap to Rate:",
    "gahungu team": "Gahungu Team",
    "failed to load reviews": "Failed to load reviews. Please check your connection.",
    "my engagement points": "My Engagement Points",
    "monetization goal": "Monetization Goal",
    threshold: "Threshold:",
    "points to reach goal": "EP to reach your goal! Keep it up! 💪",
    "goal reached": "Congratulations! You've reached your monetization goal! 🎉",
    "monetization info": "Note: After reaching {monetizationGoal.toLocaleString()} EP, you will be able to turn your points into money and withdraw it.",
    "daily summary": "Daily Summary",
    "posts liked today": "• Posts Liked Today:",
    "stories viewed today": "• Stories Viewed Today:",
    "points earned today": "• Points Earned Today:",
    "keep it up message": "Keep it up dear,our Team loves you!!",
    "secure access fee": "Secure Access Fee",
    "access fee message": "To ensure the best service, a small login access fee is required to continue.",
    "access fee": "Access Fee",
    "gahungu wallet": "Gahungu Wallet",
    "available balance": "Available Balance:",
    "default pin notice": "Notice: Your default wallet PIN is 1616. Please change it to continue.",
    "fee support message": "This fee supports the maintenance of Dr. Gahungu's pharmacy network and 24/7 availability.",
    "default pin warning": "Default PIN: 1616. Change it now!",
    "change pin to continue": "Change PIN to Continue",
    "update pin": "Update PIN",
    "pay and enter app": "Pay & Enter App",
    "retry connection": "Retry Connection",
    "wallet security": "Wallet Security",
    "enter pin to pay": "Enter PIN to authorize payment",
    "enter pin to show balance": "Enter PIN to show balance",
    "forgot pin": "Forgot PIN?",
    verify: "Verify",
    "contact admin": "Contact Admin",
    "contact admin whatsapp": "Would you like to open WhatsApp to contact the admin at +25777990118?",
    "my cart": "My Cart",
    "cart empty": "Your cart is empty!",
    "browse products": "BROWSE PRODUCTS",
    "choose payment method": "Choose Payment Method",
    "bank payment": "Bank Payment",
    "gahungu wallet balance": "Gahungu Wallet (Balance:",
    "proceed to payment": "Proceed to Payment",
    "failed to load wallet data": "Failed to load wallet data. Please check your connection.",
    ep: "EP",
    "link to website": "Link to the website",
    "click to whatsapp": "Click here to Whatsapp",
    "follow on instagram": "Follow them on Instagram",
    "follow on x": "Follow them on X",
    likes: "likes",
    "check out more here": "Check out more here",
    viewed: "Viewed",
    "ep eligible message": "Your current EP is {engagementPoints.toLocaleString()}, you are eligible to book.",
    "ep warning message": "Your current EP is less than {minEpRequired.toLocaleString()}.",
    "earn ep message": "Click here to increase your EP by watching stories, viewing posts and liking posts.",
    "customer support": "Customer Support",
    email: "Email",
    phone: "Phone",
    facebook: "Facebook",
    instagram: "Instagram",
    "terms and conditions": "Terms and Conditions",
    "last updated": "Last Updated: November 11, 2025",
    "terms introduction": "1. Introduction",
    "terms intro paragraph": "Welcome to GAHUNGU PHARMACY (\"App\", \"we\", \"us\", \"our\"). By downloading, accessing, or using our mobile application, you agree to be bound by these Terms and Conditions. If you do not agree, please do not use the App.",
    "terms medical disclaimer": "2. Medical Disclaimer",
    "terms medical disclaimer paragraph": "Always seek the advice of your physician or other qualified health provider with any questions you may have regarding a medical condition. Never disregard professional medical advice or delay in seeking it because of something you have read on this App. Reliance on any information provided by the App is solely at your own risk.",
    "terms user accounts": "3. User Accounts",
    "terms user accounts paragraph": "To access certain features, you must register for an account. You agree to provide accurate, current, and complete information during the registration process and to update such information to keep it accurate. You are responsible for safeguarding your password and for any activities or actions under your account.",
    "terms use of services": "4. Use of Services",
    "terms use of services paragraph": "You may use the App only for lawful purposes. You agree not to use the App to:\n- Purchase prescription medication without a valid prescription.\n- Violate any local, national, or international law.\n- Transmit any material that is defamatory, offensive, or otherwise objectionable.",
    "terms purchases and payments": "5. Purchases and Payments",
    "terms purchases and payments paragraph": "If you wish to purchase any product or service made available through the App, you may be asked to supply certain information relevant to your purchase. All payments made through the Gahungu Wallet are subject to the terms of our payment processing partners. We are not responsible for any errors or issues in the payment process.",
    "terms privacy": "6. Privacy",
    "terms privacy paragraph": "Your privacy is important to us. Our Privacy Policy explains how we collect, use, and share your personal information. By using this App, you agree to the collection and use of information in accordance with our Privacy Policy.",
    "terms limitation of liability": "7. Limitation of Liability",
    "terms limitation of liability paragraph": "In no event shall GAHUNGU PHARMACY, nor its directors, employees, partners, or agents, be liable for any indirect, incidental, special, consequential, or punitive damages, including without limitation, loss of profits, data, use, goodwill, or other intangible losses, resulting from your access to or use of or inability to access or use the App.",
    "terms changes to terms": "8. Changes to Terms",
    "terms changes to terms paragraph": "We reserve the right, at our sole discretion, to modify or replace these Terms at any time. We will provide notice of any changes by posting the new Terms and Conditions on this page.",
    "terms contact us": "9. Contact Us",
    "terms contact us paragraph": "If you have any questions about these Terms, please contact us at supportgahungupharmacy@gmail.com.",
  },
  rn: {
    settings: "Amasanamu",
    logout: "Gusohoka",
    confirmLogout: "Emeza Gusohoka",
    logoutMessage: "Woba ushaka gusohoka?",
    cancel: "Kureka",
    language: "Ururimi",
    dataCountry: "Igihugu c'amakuru",
    home: "Ahabanza", // Added missing key
    cart: "Igikoresho", // Added missing key
    profile: "Umwirondoro", // Added missing key
    "murahawe ikaze kwa Dr. Gahungu:": "Murahawe ikaze kwa Dr. Gahungu",
    doctors: "Doctors",
    pharmacies: "Pharmacies",
    hospitals: "Hospitals",
    insurances: "Insurances",
    explore: "Explore",
    categories: "Categories",
    "all categories": "All Categories",
    "deals of the day": "Deals of the day",
    "recommended for you": "Recommended for you",
    "featured pharmacies": "Featured Pharmacies",
    "featured hospitals": "Featured Hospitals",
    "featured insurances": "Featured Insurances",
    "featured doctors":"Featured Doctors",
    "no hospitals available": "No hospitals available",
    "no products available": "No products available",
    "no doctors available": "No doctors available",
    "no insurances available": "No insurances available",
    "no pharmacies available": "No pharmacies available",
    "no deals available": "No deals available",
    "Medecines for": "Medecines for",
    "product details": "Product Details",
    "add to cart": "Add to Cart",
    "added to cart": "Added to Cart",
    "go to cart": "Go to Cart",
    "out of stock": "Out of Stock",
    "available at": "Available at",
    locations: "Locations",
    contact: "Contact",
    price: "Price",
    "view on the map": "View on the map",
    "opening hours": "Opening hours",
    reviews: "Reviews",
    "no reviews yet": "No reviews yet",
    "write a review": "Write a review",
    submit: "Submit",
    "your review": "Your review",
    "thank you for your review": "Thank you for your review",
    "review submitted": "Review submitted",
    "review submission failed": "Review submission failed",
    "edit review": "Edit Review",
    "delete review": "Delete Review",
    mon: "MON",
    tue: "TUE",
    wed: "WED",
    thu: "THU",
    fri: "FRI",
    sat: "SAT",
    sun: "SUN",
    "accepted insurances": "Accepted Insurances",
    "insurance details": "Insurance Details",
    coverage: "Coverage",
    "contact details": "Contact Details",
    "pharmacy details": "Pharmacy Details",
    "hospital details": "Hospital Details",
    "service summary": "Service Summary",
    "admission process": "Admission Process",
    "available services": "Available Services",
    "available blood types": "Available Blood Types",
    "medical equipment": "Medical Equipment",
    "Partner Pharmacies": "Partner Pharmacies",
    "main location": "Main Location",
    "open in google maps": "Open in Google Maps",
    "doctor profile": "Doctor Profile",
    about: "About",
    "working hours": "Working Hours",
    "availability & booking": "Availability & Booking",
    "book an appointment": "Book an appointment",
    "appointment booked": "Appointment booked",
    "appointment booking failed": "Appointment booking failed",
    "see details": "See details",
    "insurance type": "Insurance Type",
    "coverage summary": "Coverage Summary",
    "claim process": "Claim Process",
    "partner hospitals": "Partner Hospitals",
    "partner pharmacies": "Partner Pharmacies",
    "office locations": "Office Locations",
    "branch office": "Branch Office",
    "all doctors": "All Doctors",
    "all pharmacies": "All Pharmacies",
    "all hospitals": "All Hospitals",
    "all insurances": "All Insurances",
    searchPlaceholder: "Search medicines, doctors, pharmacies...",
    searchPlaceholderText: "Search here with Gahungu Search...",
    "no results found for": "No results found for",
    "try different keywords": "Try different keywords",
    "searching for": "Searching for",
    "results for": "Results for",
    "recent searches": "Recent Searches",
    "clear all": "Clear All",
    "type to see suggestions": "Type at least 2 characters to see suggestions",
    "my prescriptions": "My Prescriptions",
    "covered by": "Covered by:",
    "no prescriptions found": "No results found for your prescriptions.",
    "try different spellings": "Try different spellings or fewer items.",
    payment: "Payment",
    "booking details": "Booking Details",
    doctor: "Doctor",
    date: "Date",
    time: "Time",
    type: "Type",
    online: "Online",
    "in-office": "Mu biro",
    "consultation fee": "Consultation Fee(To be Fixed by Doctors)",
    "doctor service fee": "Doctor Service Fee",
    "total amount": "Total Amount",
    "payment method": "Payment Method",
    "pay with gahungu wallet": "Pay with Gahungu Wallet",
    "pay with gahungu card": "Pay with Gahungu Card",
    "my orders": "My Orders",
    "order hash": "Order #",
    "placed on": "Placed on:",
    total: "Total:",
    "check order status": "Check your order status",
    "no orders yet": "You have no orders yet.",
    "start shopping": "Start Shopping",
    "failed to load orders": "Failed to load orders. Please check your connection.",
    retry: "Retry",
    "update profile": "Update Profile",
    "full name": "Full Name",
    "whatsapp number": "WhatsApp Number (e.g., +257...)",
    updating: "Updating...",
    "save changes": "Save Changes",
    "failed to load profile": "Failed to load profile information.",
    "my bus tickets": "My Bus Tickets",
    new: "NEW",
    origin: "Origin",
    destination: "Destination",
    seat: "Seat",
    id: "ID:",
    "scan at boarding": "Scan at boarding",
    service: "Service",
    "no tickets yet": "You don't have any tickets yet.",
    "book a jk bus": "Book a JK BUS",
    "failed to load bus tickets": "Failed to load bus tickets. Please check your connection.",
    "select your seat": "Select Your Seat",
    available: "Available",
    reserved: "Reserved",
    selected: "Selected",
    vip: "VIP",
    "vip section": "VIP SECTION (1.5x Price)",
    "standard section": "STANDARD SECTION",
    "seats selected": "Seats Selected",
    "confirm booking": "Confirm Booking",
    "buses available": "Buses Available",
    "main terminal": "Main Terminal",
    "central station": "Central Station",
    "select seat": "Select Seat",
    "no buses found": "No buses found for this specific route on this date.",
    "try another route": "Try another route",
    "my transactions": "My Transactions",
    "total wallet activity": "Total Wallet Activity",
    "review spending": "Review your recent spending and top-ups",
    "total in": "Total In",
    "total out": "Total Out",
    "filter by month": "Filter by Month",
    "view all": "View All",
    "no transactions found": "No transactions found.",
    "failed to load transactions": "Failed to load transactions. Please check your connection.",
    "confirm payment": "Confirm Payment",
    "order summary": "Order Summary",
    subtotal: "Subtotal",
    "medicine service fee": "Medicine Service Fee",
    "paying with gahungu wallet": "Paying with Gahungu Wallet",
    "confirm and pay": "Confirm & Pay",
    "enter wallet pin": "Enter Wallet PIN",
    "enter pin message": "Please enter your 4-digit PIN to confirm payment.",
    "update pin": "Update PIN",
    "verify and pay": "Verify & Pay",
    "travel with comfort": "Travel with Comfort",
    "safe and reliable journeys": "Safe and reliable journeys across the region",
    "popular routes": "Popular Routes",
    from: "From",
    to: "To",
    "origin city": "Origin City",
    "destination city": "Destination City",
    "departure date": "Departure Date",
    "search buses": "Search Buses",
    "why choose jk bus": "Why choose JK BUS?",
    "air conditioned fleet": "• Air-conditioned modern fleet",
    "experienced drivers": "• Experienced and professional drivers",
    "realtime gps tracking": "• Real-time GPS tracking for safety",
    "change pin": "Change PIN",
    "create pin": "Create PIN",
    "verify current pin": "Verify Your Current PIN",
    "enter current pin message": "Please enter your current 4-digit PIN to proceed.",
    "current pin": "Current PIN",
    "verify pin": "Verify PIN",
    "set new pin": "Set Your New PIN",
    "set transaction pin": "Set Your Transaction PIN",
    "pin authorization message": "This 4-digit PIN will be used to authorize your payments.",
    "new pin": "New PIN (4 digits)",
    "confirm new pin": "Confirm New PIN",
    update: "Update",
    "save pin": "Save PIN",
    "app reviews": "App Reviews",
    "total reviews": "total reviews",
    "highly recommended": "Highly Recommended by Users",
    "trusted companion": "Trusted healthcare companion",
    "your name": "Your Name",
    "tap to rate": "Tap to Rate:",
    "gahungu team": "Gahungu Team",
    "failed to load reviews": "Failed to load reviews. Please check your connection.",
    "my engagement points": "My Engagement Points",
    "monetization goal": "Monetization Goal",
    threshold: "Threshold:",
    "points to reach goal": "EP to reach your goal! Keep it up! 💪",
    "goal reached": "Congratulations! You've reached your monetization goal! 🎉",
    "monetization info": "Note: After reaching {monetizationGoal.toLocaleString()} EP, you will be able to turn your points into money and withdraw it.",
    "daily summary": "Daily Summary",
    "posts liked today": "• Posts Liked Today:",
    "stories viewed today": "• Stories Viewed Today:",
    "points earned today": "• Points Earned Today:",
    "keep it up message": "Keep it up dear,our Team loves you!!",
    "secure access fee": "Secure Access Fee",
    "access fee message": "To ensure the best service, a small login access fee is required to continue.",
    "access fee": "Access Fee",
    "gahungu wallet": "Gahungu Wallet",
    "available balance": "Available Balance:",
    "default pin notice": "Notice: Your default wallet PIN is 1616. Please change it to continue.",
    "fee support message": "This fee supports the maintenance of Dr. Gahungu's pharmacy network and 24/7 availability.",
    "default pin warning": "Default PIN: 1616. Change it now!",
    "change pin to continue": "Change PIN to Continue",
    "pay and enter app": "Pay & Enter App",
    "retry connection": "Retry Connection",
    "wallet security": "Wallet Security",
    "enter pin to pay": "Enter PIN to authorize payment",
    "enter pin to show balance": "Enter PIN to show balance",
    "forgot pin": "Forgot PIN?",
    verify: "Verify",
    "contact admin": "Contact Admin",
    "contact admin whatsapp": "Would you like to open WhatsApp to contact the admin at +25777990118?",
    "my cart": "My Cart",
    "cart empty": "Your cart is empty!",
    "browse products": "BROWSE PRODUCTS",
    "choose payment method": "Choose Payment Method",
    "bank payment": "Bank Payment",
    "gahungu wallet balance": "Gahungu Wallet (Balance:",
    "proceed to payment": "Proceed to Payment",
    "failed to load wallet data": "Failed to load wallet data. Please check your connection.",
    ep: "EP",
    "link to website": "Link to the website",
    "click to whatsapp": "Click here to Whatsapp",
    "follow on instagram": "Follow them on Instagram",
    "follow on x": "Follow them on X",
    likes: "likes",
    "check out more here": "Check out more here",
    viewed: "Viewed",
    "ep eligible message": "Your current EP is {engagementPoints.toLocaleString()}, you are eligible to book.",
    "ep warning message": "Your current EP is less than {minEpRequired.toLocaleString()}.",
    "earn ep message": "Click here to increase your EP by watching stories, viewing posts and liking posts.",
    "customer support": "Customer Support",
    email: "Email",
    phone: "Phone",
    facebook: "Facebook",
    instagram: "Instagram",
    "terms and conditions": "Terms and Conditions",
    "last updated": "Last Updated: November 11, 2025",
    "terms introduction": "1. Introduction",
    "terms intro paragraph": "Welcome to GAHUNGU PHARMACY (\"App\", \"we\", \"us\", \"our\"). By downloading, accessing, or using our mobile application, you agree to be bound by these Terms and Conditions. If you do not agree, please do not use the App.",
    "terms medical disclaimer": "2. Medical Disclaimer",
    "terms medical disclaimer paragraph": "Always seek the advice of your physician or other qualified health provider with any questions you may have regarding a medical condition. Never disregard professional medical advice or delay in seeking it because of something you have read on this App. Reliance on any information provided by the App is solely at your own risk.",
    "terms user accounts": "3. User Accounts",
    "terms user accounts paragraph": "To access certain features, you must register for an account. You agree to provide accurate, current, and complete information during the registration process and to update such information to keep it accurate. You are responsible for safeguarding your password and for any activities or actions under your account.",
    "terms use of services": "4. Use of Services",
    "terms use of services paragraph": "You may use the App only for lawful purposes. You agree not to use the App to:\n- Purchase prescription medication without a valid prescription.\n- Violate any local, national, or international law.\n- Transmit any material that is defamatory, offensive, or otherwise objectionable.",
    "terms purchases and payments": "5. Purchases and Payments",
    "terms purchases and payments paragraph": "If you wish to purchase any product or service made available through the App, you may be asked to supply certain information relevant to your purchase. All payments made through the Gahungu Wallet are subject to the terms of our payment processing partners. We are not responsible for any errors or issues in the payment process.",
    "terms privacy": "6. Privacy",
    "terms privacy paragraph": "Your privacy is important to us. Our Privacy Policy explains how we collect, use, and share your personal information. By using this App, you agree to the collection and use of information in accordance with our Privacy Policy.",
    "terms limitation of liability": "7. Limitation of Liability",
    "terms limitation of liability paragraph": "In no event shall GAHUNGU PHARMACY, nor its directors, employees, partners, or agents, be liable for any indirect, incidental, special, consequential, or punitive damages, including without limitation, loss of profits, data, use, goodwill, or other intangible losses, resulting from your access to or use of or inability to access or use the App.",
    "terms changes to terms": "8. Changes to Terms",
    "terms changes to terms paragraph": "We reserve the right, at our sole discretion, to modify or replace these Terms at any time. We will provide notice of any changes by posting the new Terms and Conditions on this page.",
    "terms contact us": "9. Contact Us",
    "terms contact us paragraph": "If you have any questions about these Terms, please contact us at supportgahungupharmacy@gmail.com.",
  }
};