import { create } from 'zustand';
import AsyncStorage from '@react-native-async-storage/async-storage';

export type Language = 'en' | 'fr' | 'rn';

export interface LanguageState {
  language: Language;
  setLanguage: (lang: Language) => Promise<void>;
  loadLanguage: () => Promise<void>;
}

export const useLanguageStore = create<LanguageState>((set) => ({
  language: 'en',

  setLanguage: async (lang: Language) => {
    try {
      await AsyncStorage.setItem('user_language', lang);
      set({ language: lang });
    } catch (error) {
      console.error('Error saving language:', error);
    }
  },

  loadLanguage: async () => {
    try {
      const lang = await AsyncStorage.getItem('user_language');

      if (lang) {
        set({ language: lang as Language });
      }
    } catch (error) {
      console.error('Error loading language:', error);
    }
  },
}));

export const translations = {
  en: {
    settings: "Settings",
    logout: "Logout",
    confirmLogout: "Confirm Logout",
    logoutMessage: "Are you sure you want to log out?",
    cancel: "Cancel",
    language: "Language",
    dataCountry: "Data Country",
    home: "Home",
    cart: "Cart",
    profile: "Profile",
    "murahawe ikaze kuri MELANA:": "Murahawe Ikaze kuri MELANA:",
    doctors: "Doctors",
    pharmacies: "Pharmacies",
    hospitals: "Hospitals",
    insurances: "Insurances",
    explore: "Explore",
    categories: "Categories",
    "all categories": "All Categories",
    "please check your internet connection and try again": "Please check your internet connection and try again",
    "deals of the day": "Deals of the day",
    "recommended for you": "Recommended for you",
    "featured pharmacies": "Featured Pharmacies",
    "featured hospitals": "Featured Hospitals",
    "featured insurances": "Featured Insurances",
    "featured doctors":"Featured Doctors",
    "Dieu avec Gahungu, Votre Santé est assurée": "God with Gahungu,Your Health is guaranteed.",
    "no hospitals available": "No hospitals available",
    "no products available": "No products available",
    "no doctors available": "No doctors available",
    "no doctors found":"No doctors found",
    "unknown doctor": "Unknown Doctor",
    confirmed: "Confirmed",
    cancelled: "Cancelled",
    pending: "Pending",
    "ticket number": "Ticket Number",
    "online consultation": "Online Consultation",
    "in-office visit": "In-Office Visit",
    "with melana": "with Dr. Gahungu App",
    complete: "Complete",
    incomplete: "Incomplete",
    refunded: "Refunded",
    paid: "Paid",
    "failed to load appointments": "Failed to load appointments. Please check your connection.",
    "no appointments found": "No appointments found.",
    "no insurances available": "No insurances available",
    "no pharmacies available": "No pharmacies available",
    "no deals available": "No deals available",
    "product details": "Product Details",
    "add to cart": "Add to Cart",
    "added to cart": "Added to Cart",
    "go to cart": "Go to Cart",
    "out of stock": "Out of Stock",
    "available at": "Available at",
    locations: "Locations",
    contact: "Contact",
    price: "Price",
    "view on map": "View on Map",
    "opening hours": "Opening hours",
    closed: "Closed",
    reviews: "Reviews",
    yes: "Yes",
    no: "No",
    "call car": "Call a car",
    "no reviews yet": "No reviews yet",
    "write a review": "Write a review",
    submit: "Submit",
    "your review": "Your review",
    "thank you for your review": "Thank you for your review",
    "review submitted": "Review submitted",
    "review submission failed": "Review submission failed",
    "edit review": "Edit Review",
    "doctor not found": "Doctor not found.",
    "hospital not found": "Hospital not found.",
    "delete review": "Delete Review",
    mon: "MON",
    tue: "TUE",
    wed: "WED",
    thu: "THU",
    fri: "FRI",
    sat: "SAT",
    sun: "SUN",
    "accepted insurances": "Accepted Insurances",
    "my appointments": "My Appointments",
    "appointments description": "View your scheduled doctor visits",
    "transactions description": "Check your wallet history",
    "bus booking description": "Travel with comfort",
    "bus tickets description": "View your reserved seats",
    "reviews description": "See what others are saying about the app",
    "pin description": "Set or change your payment PIN",
    "support description": "Gahungu is glad to help",
    "update profile description": "Manage your personal information",
    "settings description": "App settings and preferences",
    "insurance details": "Insurance Details",
    coverage: "Coverage",
    "contact details": "Contact Details",
    "pharmacy details": "Pharmacy Details",
    "hospital details": "Hospital Details",
    "service summary": "Service Summary",
    "admission process": "Admission Process",
    "available services": "Available Services",
    "available blood types": "Available Blood Types",
    "medical equipment": "Medical Equipment",
    "Partner Pharmacies": "Partner Pharmacies",
    "main location": "Main Location",
    "open in google maps": "Open in Google Maps",
    "doctor profile": "Doctor Profile",
    about: "About",
    "working hours": "Working Hours",
    "availability & booking": "Availability & Booking",
    "available times": "Available Times",
    "book online": "Book Online",
    "book in-office": "Book In-Office",
    "book an appointment": "Book an appointment",
    "appointment booked": "Appointment booked",
    "view my transactions": "View My Transactions",
    "transaction pin": "Transaction PIN",
    version: "Version",
    "appointment booking failed": "Appointment booking failed",
    "see details": "See details",
    "insurance type": "Insurance Type",
    "coverage summary": "Coverage Summary",
    "claim process": "Claim Process",
    "partner hospitals": "Partner Hospitals",
    "partner pharmacies": "Partner Pharmacies",
    "office locations": "Office Locations",
    "branch office": "Branch Office",
    "all doctors": "All Doctors",
    "pay and book": "Pay & Book",
    "payment successful": "Payment Successful!",
    "redirecting to appointments": "Redirecting to appointments...",
    "insufficient wallet balance": "Insufficient wallet balance.",
    "please log in to book": "Please log in to book.",
    "duplicate booking message": "You already have a booking with this doctor at this time.",
    "failed to check existing bookings": "Failed to check existing bookings.",
    "incorrect pin": "Incorrect PIN.",
    "no image available": "No Image Available",
    "all pharmacies": "All Pharmacies",
    "all hospitals": "All Hospitals",
    "all insurances": "All Insurances",
    searchPlaceholder: "Search medicines, doctors, pharmacies...",
    searchPlaceholderText: "Search here with Gahungu Search...",
    "no results found for": "No results found for",
    "try different keywords": "Try different keywords",
    "searching for": "Searching for",
    "results for": "Results for",
    "recent searches": "Recent Searches",
    "clear all": "Clear All",
    "type to see suggestions": "Type at least 2 characters to see suggestions",
    "my prescriptions": "My Prescriptions",
    "covered by": "Covered by:",
    "no prescriptions found": "No results found for your prescriptions.",
    "try different spellings": "Try different spellings or fewer items.",
    payment: "Payment",
    "booking details": "Booking Details",
    doctor: "Doctor",
    date: "Date",
    time: "Time",
    type: "Type",
    online: "Online",
    "in-office": "In-Office",
    "consultation fee": "Consultation Fee(To be Fixed by Doctors)",
    "doctor service fee": "Doctor Service Fee",
    "total amount": "Total Amount",
    "payment method": "Payment Method",
    "pay with gahungu wallet": "Pay with Gahungu Wallet",
    "pay with gahungu card": "Pay with Gahungu Card",
    "my orders": "My Orders",
    "order hash": "Order #",
    "placed on": "Placed on:",
    total: "Total:",
    "check order status": "Check your order status",
    "no orders yet": "You have no orders yet.",
    "start shopping": "Start Shopping",
    "failed to load orders": "Failed to load orders. Please check your connection.",
    retry: "Retry",
    "update profile": "Update Profile",
    "full name": "Full Name",
    "whatsapp number": "WhatsApp Number (e.g: +257...)",
    updating: "Updating...",
    "save changes": "Save Changes",
    "failed to load profile": "Failed to load profile information.",
    "my bus tickets": "My Bus Tickets",
    new: "NEW",
    origin: "Origin",
    destination: "Destination",
    seat: "Seat",
    id: "ID:",
    "scan at boarding": "Scan at boarding",
    service: "Service",
    "no tickets yet": "You don't have any tickets yet.",
    "book a jk bus": "Book a JK BUS",
    "failed to load bus tickets": "Failed to load bus tickets. Please check your connection.",
    "select your seat": "Select Your Seat",
    available: "Available",
    reserved: "Reserved",
    selected: "Selected",
    vip: "VIP",
    "vip section": "VIP SECTION (1.5x Price)",
    "standard section": "STANDARD SECTION",
    "seats selected": "Seats Selected",
    "confirm booking": "Confirm Booking",
    "buses available": "Buses Available",
    "main terminal": "Main Terminal",
    "central station": "Central Station",
    "select seat": "Select Seat",
    "no buses found": "No buses found for this specific route on this date.",
    "try another route": "Try another route",
    "my transactions": "My Transactions",
    "total wallet activity": "Total Wallet Activity",
    "review spending": "Review your recent spending and top-ups",
    "total in": "Total In",
    "total out": "Total Out",
    "filter by month": "Filter by Month",
    "view all": "View All",
    "no transactions found": "No transactions found.",
    "failed to load transactions": "Failed to load transactions. Please check your connection.",
    "confirm payment": "Confirm Payment",
    "order summary": "Order Summary",
    subtotal: "Subtotal",
    "medicine service fee": "Medicine Service Fee",
    "paying with gahungu wallet": "Paying with Gahungu Wallet",
    "confirm and pay": "Confirm & Pay",
    "enter wallet pin": "Enter Wallet PIN",
    "enter pin message": "Please enter your 4-digit PIN to confirm payment.",
    "verify and pay": "Verify & Pay",
    "travel with comfort": "Travel with Comfort",
    "safe and reliable journeys": "Safe and reliable journeys across the region",
    "popular routes": "Popular Routes",
    from: "From",
    to: "To",
    "origin city": "Origin City",
    "destination city": "Destination City",
    "departure date": "Departure Date",
    "search buses": "Search Buses",
    "why choose jk bus": "Why choose JK BUS?",
    "air conditioned fleet": "• Air-conditioned modern fleet",
    "experienced drivers": "• Experienced and professional drivers",
    "realtime gps tracking": "• Real-time GPS tracking for safety",
    "change pin": "Change PIN",
    "create pin": "Create PIN",
    "verify current pin": "Verify Your Current PIN",
    "enter current pin message": "Please enter your current 4-digit PIN to proceed.",
    "current pin": "Current PIN",
    "verify pin": "Verify PIN",
    "set new pin": "Set Your New PIN",
    "update pin": "Update PIN",
    "set transaction pin": "Set Your Transaction PIN",
    "pin authorization message": "This 4-digit PIN will be used to authorize your payments.",
    "new pin": "New PIN (4 digits)",
    "confirm new pin": "Confirm New PIN",
    update: "Update",
    "save pin": "Save PIN",
    "app reviews": "App Reviews",
    "total reviews": "total reviews",
    "highly recommended": "Highly Recommended by Users",
    "trusted companion": "Trusted healthcare companion",
    "your name": "Your Name",
    "tap to rate": "Tap to Rate:",
    "gahungu team": "Gahungu Team",
    "failed to load reviews": "Failed to load reviews. Please check your connection.",
    "my engagement points": "My Engagement Points",
    "monetization goal": "Monetization Goal",
    threshold: "Threshold:",
    "points to reach goal": "EP to reach your goal! Keep it up! 💪",
    "goal reached": "Congratulations! You've reached your monetization goal! 🎉",
    "monetization info": "Note: After reaching {monetizationGoal.toLocaleString()} EP, you will be able to turn your points into money and withdraw it.",
    "daily summary": "Daily Summary",
    "posts liked today": "• Posts Liked Today:",
    "stories viewed today": "• Stories Viewed Today:",
    "points earned today": "• Points Earned Today:",
    "keep it up message": "Keep it up dear,our Team loves you!!",
    "secure access fee": "Secure Access Fee",
    "access fee message": "To ensure the best service, a small login access fee is required to continue.",
    "access fee": "Access Fee",
    "gahungu wallet": "Gahungu Wallet",
    "available balance": "Available Balance:",
    "default pin notice": "Notice: Your default wallet PIN is 1616. Please change it to continue.",
    "fee support message": "This fee supports the maintenance of Dr. Gahungu's pharmacy network and 24/7 availability.",
    "default pin warning": "Default PIN: 1616. Change it now!",
    "change pin to continue": "Change PIN to Continue",
    "pay and enter app": "Pay & Enter App",
    "retry connection": "Retry Connection",
    "wallet security": "Wallet Security",
    "enter pin to pay": "Enter PIN to authorize payment",
    "enter pin to show balance": "Enter PIN to show balance",
    "forgot pin": "Forgot PIN?",
    verify: "Verify",
    "no data": "No data available",
    "no transactions to export": "No transactions to export.",
    "transaction report": "Transaction Report",
    filter: "Filter",
    description: "Description",
    amount: "Amount",
    "generated by app on": "Generated by app on",
    error: "An error occurred. Please check your connection.",
    "failed to generate pdf": "Failed to generate PDF. Please check your connection.",
    "wallet activity subtext": "Here's a summary of your recent activity in Gahungu Wallet.",
    "all transactions": "All Transactions",
    "contact admin": "Contact Admin",
    "contact admin whatsapp": "Would you like to open WhatsApp to contact the admin at +25777990118?",
    "my cart": "My Cart",
    "cart empty": "Your cart is empty!",
    "browse products": "BROWSE PRODUCTS",
    "choose payment method": "Choose Payment Method",
    "bank payment": "Bank Payment",
    "gahungu wallet balance": "Gahungu Wallet (Balance:",
    "proceed to payment": "Proceed to Payment",
    "failed to load wallet data": "Failed to load wallet data. Please check your connection.",
    ep: "EP",
    "link to website": "Link to the website",
    "click to whatsapp": "Click here to Whatsapp",
    "follow on instagram": "Follow them on Instagram",
    "follow on x": "Follow them on X",
    likes: "likes",
    "check out more here": "Check out more here",
    viewed: "Viewed",
    "ep eligible message": "Your current EP is {engagementPoints.toLocaleString()}, you are eligible to book.",
    "ep warning message": "Your current EP is less than {minEpRequired.toLocaleString()}.",
    "earn ep message": "Click here to increase your EP by watching stories, viewing posts and liking posts.",
    "customer support": "Customer Support",
    email: "Email",
    phone: "Phone",
    facebook: "Facebook",
    instagram: "Instagram",
    "terms and conditions": "Terms and Conditions",
    "last updated": "Last Updated: November 11, 2025",
    "terms introduction": "1. Introduction",
    "terms intro paragraph": "Welcome to GAHUNGU PHARMACY (\"App\", \"we\", \"us\", \"our\"). By downloading, accessing, or using our mobile application, you agree to be bound by these Terms and Conditions. If you do not agree, please do not use the App.",
    "terms medical disclaimer": "2. Medical Disclaimer",
    "terms medical disclaimer paragraph": "Always seek the advice of your physician or other qualified health provider with any questions you may have regarding a medical condition. Never disregard professional medical advice or delay in seeking it because of something you have read on this App. Reliance on any information provided by the App is solely at your own risk.",
    "terms user accounts": "3. User Accounts",
    "terms user accounts paragraph": "To access certain features, you must register for an account. You agree to provide accurate, current, and complete information during the registration process and to update such information to keep it accurate. You are responsible for safeguarding your password and for any activities or actions under your account.",
    "terms use of services": "4. Use of Services",
    "terms use of services paragraph": "You may use the App only for lawful purposes. You agree not to use the App to:\n- Purchase prescription medication without a valid prescription.\n- Violate any local, national, or international law.\n- Transmit any material that is defamatory, offensive, or otherwise objectionable.",
    "terms purchases and payments": "5. Purchases and Payments",
    "terms purchases and payments paragraph": "If you wish to purchase any product or service made available through the App, you may be asked to supply certain information relevant to your purchase. All payments made through the Gahungu Wallet are subject to the terms of our payment processing partners. We are not responsible for any errors or issues in the payment process.",
    "terms privacy": "6. Privacy",
    "terms privacy paragraph": "Your privacy is important to us. Our Privacy Policy explains how we collect, use, and share your personal information. By using this App, you agree to the collection and use of information in accordance with our Privacy Policy.",
    "terms limitation of liability": "7. Limitation of Liability",
    "terms limitation of liability paragraph": "In no event shall GAHUNGU PHARMACY, nor its directors, employees, partners, or agents, be liable for any indirect, incidental, special, consequential, or punitive damages, including without limitation, loss of profits, data, use, goodwill, or other intangible losses, resulting from your access to or use of or inability to access or use the App.",
    "terms changes to terms": "8. Changes to Terms",
    "terms changes to terms paragraph": "We reserve the right, at our sole discretion, to modify or replace these Terms at any time. We will provide notice of any changes by posting the new Terms and Conditions on this page.",
    "terms contact us": "9. Contact Us",
    "terms contact us paragraph": "If you have any questions about these Terms, please contact us at supportgahungupharmacy@gmail.com.",
    "no medicines found for this category": "No medicines found for this category.",
    "medicines for": "Medicines for",
    "leave app":"Leave App",
    "open whatsapp":"Open WhatsApp",
    "insurance not found": "Insurance not found.",
    "standard plan": "Standard Plan",
    "no plan details available": "No plan details available.",
    "no office locations available": "No office locations available.",
    "no contact details available": "No contact details available.",
    "leave app email message": "You may quit the app to send an email. Do you want to continue?",
    "leave app website message": "You may quit the app to visit this website. Do you want to continue?",
    office: "Office",
    web: "Web",
    "you are about to leave the app to open Google Maps. do you want to continue?": "You are about to leave the app to open Google Maps. Do you want to continue?",
    "open google maps": "Open Google Maps",
    "fill all fields": "Please fill in all fields.",
    "auth error": "Authentication error. Please log in again.",
    "login to review": "Please log in to write a review.",
    "review updated": "Review updated",
    "changes saved": "Changes saved",
    "thanks feedback": "Thanks for your feedback!",
    "failed submit review": "Failed to submit review. Please check your connection.",
    "failed update review": "Failed to update review. Please check your connection.",
    "failed delete review": "Failed to delete review. Please check your connection.",
    "something went wrong": "Something went wrong. Please check your connection.",
    "confirm delete review": "Are you sure you want to delete your review?",
    "review deleted": "Review deleted",
    delete: "Delete",
    "pin updated": "PIN updated successfully!",
    "connection error": "Connection error. Please check your internet connection and try again.",
    "your comment": "Your comment",
    "support intro": "Have questions or need help with your order? Reach out to us through any of the channels below.",
    "leave app whatsapp message": "You are about to leave the app to open WhatsApp. Do you want to continue?",
    "cannot open url": "Don't know how to open this URL:",
    "default pin alert message": "Your PIN is currently \"1616\" (default). For your security, you must change it before you can pay the access fee.",
    "welcome message": "Welcome to GAHUNGU PHARMACY",
    "whatsapp hint": "Start with country code like: +25777990118",
    "enter whatsapp": "Enter your WhatsApp number",
    "whatsapp required": "WhatsApp number is required.",
    "password hint": "Enter your secret code",
    "enter password": "Enter your password",
    "password required": "Password is required.",
    "country hint": "Select the country you want to search in",
    "country required": "Please select a country.",
    "login": "Login",
    "forgot password": "Forgot Password?",
    "dont have account": "Don’t have an account? ",
    "register": "Register",
    "login error": "Login Error",
    "invalid response": "Invalid server response. Check console logs.",
    "login failed alert": "Login failed ❌",
    "create account": "Create an Account",
    "registration welcome": "Welcome to Dr. Gahungu, You Already healed!",
    "fullname hint": "Enter your name like: GAHUNGU",
    "fullname required": "Full name is required.",
    "password": "Password",
    "password hint long": "Use letters and numbers, at least 8 chars. e.g: Gahungu12345",
    "password must be at least 8 characters": "Password must be at least 8 characters.",
    "password must contain both letters and numbers": "Password must contain both letters and numbers.",
    "confirm password hint": "Repeat the password you just entered",
    "confirm password required": "Please confirm your password.",
    "passwords dont match": "Passwords do not match.",
    "select country": "Select your country",
    "search country": "Search country...",
    "country hint long": "Click and select the country you are in now",
    "whatsapp format error": "Enter a valid number with country code (e.g: +257...).",
    "whatsapp registered error": "This WhatsApp number is already registered.",
    "error checking whatsapp": "Error checking WhatsApp number.",
    "checking whatsapp": "Checking WhatsApp number...",
    "secret question label": "Which part of your body do you love the most? Remember it!!",
    "select answer": "Select an answer",
    "secret answer required": "Please answer the secret question.",
    "male": "Male",
    "female": "Female",
    "terms agree start": "By clicking this checkbox, you agree to",
    "confirm details title": "Confirm Your Details",
    "confirm details message": "Is this information correct?",
    "registered alert title": "Registered Successfully ✅",
    "registered alert message": "You can now log in!",
    "registration failed": "Registration failed ❌",
    head: "Head",
    legs: "Legs",
    lips: "Lips",
    body: "Body",
    eyes: "Eyes",
    fingers: "Fingers",
    "secret answer": "Secret Answer",
    "confirm password": "Confirm Password",
    country: "Current Country",
    "insufficient engagement points": "Insufficient Engagement Points",
  "ep required to book message": "You need {minEpRequired} EP to book. Earn more by watching stories, viewing posts, and liking content!",
  "authentication error": "Authentication Error",
  "wallet error": "Wallet Error",
  "failed to fetch balance": "Failed to fetch balance.",
  "insufficient balance": "Insufficient Balance",
  "please add funds to wallet": "Please add funds to your wallet.",
  "failed to verify wallet balance": "Failed to verify wallet balance.",
  "invalid pin": "Invalid PIN",
  "please enter 4-digit pin": "Please enter a 4-digit PIN.",
  "booking confirmed": "Booking Confirmed 🎉",
  "reserved seats message": "Reserved {seatsLength} seats for your trip!",
  "booking failed": "Booking Failed",
  "something went wrong booking": "Something went wrong while reserving your seat.",
  "not available": "N/A",
  "seats": "Seats",
  "seat price": "Seat Price",
  "bus service fee": "Bus Service Fee",
  "pay from gahungu wallet": "Pay from Gahungu Wallet",
  "checking eligibility": "Checking your eligibility...",
  "eligible to book message": "Your current EP is {engagementPoints}, you are eligible to book.",
  "ep less than required message": "Your current EP is less than {minEpRequired}.",
  "earn ep by engaging": "Click here to increase your EP by watching stories, viewing posts and liking posts.",
  "enter pin": "Enter PIN",
  "dashboardOverview": "Dashboard Overview",
  "loadingStats": "Loading stats...",
  "totalCustomers": "Total Customers",
  "totalProducts": "Total Products",
  "totalRevenue": "Total Revenue",
  "totalPendingOrders": "Pending Orders",
  "totalViews": "Total Views",
  "withdraw": "Withdraw",
  "withdrawSoon": "The team is implementing it for soon",
  "revenueLast7Days": "Revenue (Last 7 Days)",
  "ordersLast7Days": "Orders (Last 7 Days)",
  "profileViewsLast7Days": "Profile Views (Last 7 Days)",
  "recentActivity": "Recent Activity",
  "orderId": "Order ID",
  "noRecentOrders": "No recent orders",
  "welcomeGreeting": "Greetings and welcome dear",
  "welcomeGreetingSuffix": "on Dr. Gahungu Platform.",
  "myStock": "My Stock",
  "orders": "Orders",
  "myPharmacy": "My pharmacy",
  "getApprovedFirst": "You need to be approved first",
  "updatePasswordFail": "Failed to update password",
  "updatePasswordSuccess": "Password updated successfully",
  "underReview": "Under Review",
  "pendingStatusMessage": "Your application is currently being reviewed by our team.",
  "approved": "Approved",
  "loadingForm": "Loading Form...",
  "editResubmitApp": "Edit and Resubmit Application",
  "stockManagement": "My Stock Management",
  "editItem": "Edit Item",
  "addNewItem": "Add New Item",
  "itemName": "Item Name",
  "originalPrice": "Orig. Price",
  "quantity": "Quantity",
  "selectCategory": "Select Category",
  "applicableInsurances": "Applicable Insurances",
  "uploadImage": "Upload Image",
  "changeImage": "Change Image",
  "updateItem": "Update Item",
  "addItem": "Add Item",
  "saving": "Saving...",
  "searchItemsPlaceholder": "Search items...",
  "noItemsInStock": "No items in stock",
  "noItemsMatchSearch": "No items match your search",
  "inStock": "In Stock",
  "outOfStock": "Out-of-Stock",
  "incomingOrders": "Incoming Orders",
  "customer": "Customer",
  "viewItems": "View Items",
  "printInvoice": "Print Invoice",
  "noBookingsFound": "No orders found",
  "openingHoursLabel": "Opening Hours",
  "hours24": "24 Hours",
  "payment summary": "Payment Summary",
  "change PIN":"PIN verified. You can now set a new one",
  "pin mismatch":"PINs do not match. Please try again.",
  "failed to update pin":"Failed to update PIN. Please check your connection.",
  "pin must":"PIN must be a 4-digit number.",
  "confirm update": "Confirm Update",
  "update profile logout message": "Updating your profile information will log you out automatically. Do you wish to continue?",
  "profile updated success message": "Profile updated successfully! For security reasons, you will now be logged out. Please log in again with your updated credentials.",
  "leave app facebook message": "You may quit the app to visit Facebook. Do you want to continue?",
  "leave app instagram message": "You may quit the app to visit Instagram. Do you want to continue?",
  "leave app twitter message": "You may quit the app to visit X. Do you want to continue?",
  "missing order details": "Missing order details.",
  "unexpected server response": "Unexpected server response.",
  "order failed": "Order Failed",
  "failed create order": "Failed to create order. Please try again.",
  "payment failed": "Payment Failed",
  "please try again": "Please try again.",
  "order placed message": "Your order {orderId} has been placed!",
  "order details": "Order Details",
  "items": "Items",
  "item": "Item",
  "sold by": "Sold by:",
  "status": "Status:",
  "no items found": "No items found in this order.",
  "order confirmation": "Order Confirmation",
  "qr verification help": "Present this QR code at the pharmacy for verification.",
  "download invoice": "Download Invoice",
  "order not found": "Order Not Found",
  "order details not found": "Order details could not be found.",
  "wallet payment maintenance": "Dr. IR. Gahungu is working on it, coming soon!",
  "add a comment": "Add a Comment",
  "commenting as": "Commenting as",
  "on post": "On Post",
  "create username": "Create Username",
  "username required": "Username is required.",
  "username format error": "Username must be 3-15 characters long and can only contain letters, numbers, and underscores.",
  "login to continue": "Please log in to continue.",
  "success": "Success",
  "username updated success": "Username updated successfully!",
  "failed to update username": "Failed to update username.",
  "create username title": "Create Username",
  "card maintenance": "Card payments are currently under maintenance.",
  "comment submitted":"Comment submitted successfully!",
  "create username message": "Please create a username to comment on posts and engage with the community.",
  "comment submitted message": "Your comment has been posted!",
  "enter username": "Enter your desired username",
  "failed to submit comment": "Comment failed to be Submitted",
  "orders description": "Check the status of your orders",
  "update username": "Update Username",
  "notifications": "Notifications",
  "no notifications yet": "No notifications yet.",
  "mentioned you in a comment": "mentioned you in a comment",
  "replied to your comment": "replied to your comment",
  "username hint": "3-15 characters long and can only contain letters, numbers, and underscores.",
  username: "Username",
  "write your comment here...": "write your comment here...",
  "edit your application": "Edit Your Application",
  "welcome doctor application": "Welcome Doctor",
  "needs attention": "Your Application Needs Attention",
  "rejection reason label": "Reason for rejection:",
  "rejection instructions": "Please review your information, make the necessary changes, and resubmit your application.",
  "specialty": "Specialty",
  "country of origin": "Country of Origin",
  "bio": "Bio",
  "bio placeholder": "A brief biography of the doctor...",
  "payment id": "Payment ID",
  "payment id placeholder": "Your Payment ID",
  "whatsapp hint doctor": "Start by your country code like +12345678",
  "password placeholder doctor": "Create a password",
  "doctor image": "Doctor Image",
  "choose image": "Choose image",
  "doctor terms": "I hereby agree and accept the terms and conditions of Dr. Gahungu.",
  "resubmit form": "Resubmit Form",
  "submit form": "Submit Form",
  "application updated success": "Application updated successfully! We will review it shortly.",
  "application submitted success": "Application submitted successfully! Login to check your status.",
  "submitting": "Submitting...",
  "passwordsMatchError": "New passwords do not match",
  "incorrectCurrentPassword": "Incorrect Current Password",
  "enterCurrentPassword": "Please enter your current password",
  "passwordTooShort": "New password must be at least 6 characters",
  "updatePasswordError": "An error occurred while updating the password",
  timesCommaSeparated: "Times (comma separated)",
  bookingType: "Booking Type",
  onlineFee: "Online Fee",
  officeFee: "Office Fee",
  remove: "Remove",
  day: "Day",
  start: "Start",
  end: "End",
  breakStart: "Break Start",
  breakEnd: "Break End",
  inOffice: "In Office",
  both: "Both",
  fee: "Fee",
  "failed to update profile": "Failed to update profile. Please check your connection.",
  },

  fr: {
  "failed to update profile": "Échec de la mise à jour du profil. Veuillez vérifier votre connexion.",
  "failed to load profile": "Échec du chargement des informations de profil.",
  "failed to load appointments": "Échec du chargement des rendez-vous. Veuillez vérifier votre connexion.",
  "write your comment here...": "Écrivez votre commentaire ici...",
  username: "Nom d'Utilisateur",
  "update username": "Mettre à jour le nom d'utilisateur",
  "username hint": "3 et 15 caractères et ne peut contenir que des lettres, des chiffres et des underscores.",
  "username required": "Le nom d'utilisateur est requis.",
  "username format error": "Le nom d'utilisateur doit contenir entre 3 et 15 caractères et ne peut contenir que des lettres, des chiffres et des underscores.",
  "login to continue": "Veuillez vous connecter pour continuer.",
  "success": "Succès",
  "username updated success": "Nom d'utilisateur mis à jour avec succès !",
  settings: "Paramètres",
  logout: "Se déconnecter",
  confirmLogout: "Confirmer la déconnexion",
  logoutMessage: "Êtes-vous sûr de vouloir vous déconnecter ?",
  cancel: "Annuler",
  language: "Langue",
  dataCountry: "Pays des données",
  home: "Accueil",
  cart: "Panier",
  profile: "Profil",
  "murahawe ikaze kuri MELANA:": "Murahawe Ikaze kuri MELANA:",
  "Dieu avec Gahungu, Votre Santé est assurée": "Dieu avec Gahungu,Votre Santé est assurée.",
  doctors: "Docteurs",
  pharmacies: "Pharmacies",
  hospitals: "Hôpitaux",
  insurances: "Assurances",
  explore: "Explorer",
  categories: "Catégories",
  "recent searches": "Recherches récentes",
  "please check your internet connection and try again": "Veuillez vérifier votre connexion Internet et réessayer",
  "all categories": "Toutes les catégories",
  "deals of the day": "Offres du jour",
  "recommended for you": "Recommandé pour vous",
  "featured pharmacies": "Pharmacies en collaboration",
  "featured hospitals": "Hôpitaux en collaboration",
  "featured insurances": "Assurances en collaboration",
  "featured doctors": "Docteurs en collaboration",
  "product details": "Détails du produit",
  "add to cart": "Ajouter au panier",
  "added to cart": "Ajouté au panier",
  "go to cart": "Aller au panier",
  "out of stock": "Rupture de stock",
  "available at": "Disponible chez",
  "no products available": "Aucun produit disponible",
  "no doctors available": "Aucun Docteur disponible",
  "no insurances available": "Aucune assurance disponible",
  "no pharmacies available": "Aucune pharmacie disponible",
  "no deals available": "Aucune offre disponible",
  "no hospitals available": "Aucun hôpital disponible",
  "unknown doctor": "Unknown Doctor",
  confirmed: "Confirmé",
  cancelled: "Annulé",
  pending: "En attente",
  "ticket number": "Numéro de ticket",
  "online consultation": "Consultation en ligne",
  "in-office visit": "Visite au cabinet",
  "with melana": "avec l'application du Dr. Gahungu",
  complete: "Complété",
  incomplete: "Incomplet",
  refunded: "Remboursé",
  paid: "Payé",
  "no appointments found": "Aucun rendez-vous trouvé.",
  locations: "Emplacements",
  contact: "Contact",
  "all transactions": "Toutes les transactions",
  price: "Prix",
  "view on map": "Voir sur la carte",
  "opening hours": "Heures d'ouverture",
  closed: "Fermé",
  reviews: "Avis",
  yes: "Oui",
  no: "Non",
  "call car": "Appeler un véhicule",
  "no reviews yet": "Aucun avis pour le moment",
  "write a review": "Écrire un avis",
  submit: "Soumettre",
  "your review": "Votre avis",
  "thank you for your review": "Merci pour votre avis",
  "review submitted": "Avis soumis",
  "review submission failed": "Échec de l'envoi de l'avis",
  "edit review": "Modifier l'avis",
  "doctor not found": "Docteur non trouvé.",
  "hospital not found": "Hôpital non trouvé.",
  "delete review": "Supprimer l'avis",
  "my appointments": "Mes rendez-vous",
  "orders description": "Vérifiez l'état de votre commande",
  "appointments description": "Voir vos visites chez le médecin",
  "transactions description": "Consultez l'historique de votre portefeuille",
  "bus booking description": "Voyagez confortablement",
  "bus tickets description": "Voir vos places réservées",
  "reviews description": "Voir ce que les autres disent de l'application",
  "pin description": "Définir ou modifier votre PIN de paiement",
  "support description": "Gahungu est ravi de vous aider",
  "update profile description": "Gérer vos informations personnelles",
  "settings description": "Paramètres et préférences de l'application",
  mon: "LUN",
  tue: "MAR",
  wed: "MER",
  thu: "JEU",
  fri: "VEN",
  sat: "SAM",
  sun: "DIM",
  "accepted insurances": "Assurances acceptées",
  "insurance details": "Détails de l'assurance",
  coverage: "Couverture",
  "contact details": "Coordonnées",
  "pharmacy details": "Détails de la pharmacie",
  "hospital details": "Détails de l'hôpital",
  "service summary": "Résumé du service",
  "admission process": "Processus d'admission",
  "available services": "Services disponibles",
  "available blood types": "Groupes sanguins disponibles",
  "medical equipment": "Équipements médicaux",
  "Partner Pharmacies": "Pharmacies partenaires",
  "main location": "Emplacement principal",
  "open in google maps": "Ouvrir dans Google Maps",
  "doctor profile": "Profil du médecin",
  about: "À propos",
  "working hours": "Heures de travail",
  "availability & booking": "Disponibilité et réservation",
  "available times": "Horaires disponibles",
  "book online": "Réserver en ligne",
  "book in-office": "Réserver au cabinet",
  "view my transactions": "Voir mes transactions",
  "transaction pin": "PIN de transaction",
  version: "Version",
  "book an appointment": "Prendre rendez-vous",
  "appointment booked": "Rendez-vous réservé",
  "appointment booking failed": "Échec de la réservation",
  "see details": "Voir les détails",
  "no doctors found":"Aucun docteur trouvé",
  "insurance type": "Type d'assurance",
  "coverage summary": "Résumé de la couverture",
  "claim process": "Processus de réclamation",
  "partner hospitals": "Hôpitaux partenaires",
  "partner pharmacies": "Pharmacies partenaires",
  "office locations": "Emplacements des bureaux",
  "branch office": "Succursale",
  "all doctors": "Tous les médecins",
  "pay and book": "Payer et réserver",
  "payment successful": "Paiement réussi !",
  "redirecting to appointments": "Redirection vers les rendez-vous...",
  "insufficient wallet balance": "Solde du portefeuille insuffisant.",
  "please log in to book": "Veuillez vous connecter pour réserver.",
  "duplicate booking message": "Vous avez déjà une réservation avec ce docteur à cette heure.",
  "failed to check existing bookings": "Échec de la vérification des réservations existantes.",
  "incorrect pin": "Code PIN incorrect.",
  "no image available": "Aucune image disponible",
  "all pharmacies": "Toutes les pharmacies",
  "all hospitals": "Tous les hôpitaux",
  "all insurances": "Toutes les assurances",
  searchPlaceholder: "Rechercher des médicaments, médecins, pharmacies...",
  searchPlaceholderText: "Recherchez ici avec Gahungu Search...",
  "no results found for": "Aucun résultat trouvé pour",
  "try different keywords": "Essayez d'autres mots-clés",
  "searching for": "Recherche de",
  "results for": "Résultats pour",
  "clear all": "Tout effacer",
  "type to see suggestions": "Tapez au moins 2 caractères pour voir les suggestions",
  "my prescriptions": "Mes ordonnances",
  "covered by": "Couvert par :",
  "no prescriptions found": "Aucun résultat trouvé pour vos ordonnances.",
  "try different spellings": "Essayez d'autres orthographes ou moins d'éléments.",
  payment: "Paiement",
  "booking details": "Détails de la réservation",
  doctor: "Docteur",
  date: "Date",
  time: "Heure",
  type: "Type",
  online: "En ligne",
  "in-office": "En cabinet",
  "consultation fee": "Frais de consultation (à fixer par les médecins)",
  "doctor service fee": "Frais de service du Docteur",
  "total amount": "Montant total",
  "payment method": "Méthode de paiement",
  "pay with gahungu wallet": "Payer avec Gahungu Wallet",
  "pay with gahungu card": "Payer avec la carte Gahungu",
  "my orders": "Mes commandes",
  "order hash": "Commande #",
  "placed on": "Passée le :",
  total: "Total :",
  "check order status": "Vérifiez l'état de votre commande",
  "no orders yet": "Vous n'avez pas encore de commandes.",
  "start shopping": "Commencer les achats",
  "failed to load orders": "Impossible de charger les commandes. Veuillez vérifier votre connexion.",
  retry: "Réessayer",
  "update profile": "Mettre à jour le profil",
  "full name": "Nom complet",
  "whatsapp number": "Numéro WhatsApp (ex : +257...)",
  updating: "Mise à jour...",
  "save changes": "Enregistrer les modifications",
  "my bus tickets": "Mes billets de bus",
  new: "NOUVEAU",
  origin: "Origine",
  destination: "Destination",
  seat: "Siège",
  id: "ID :",
  "scan at boarding": "Scanner à l'embarquement",
  service: "Service",
  "no tickets yet": "Vous n'avez pas encore de billets.",
  "book a jk bus": "Réserver un bus JK",
  "failed to load bus tickets": "Impossible de charger les billets de bus. Veuillez vérifier votre connexion.",
  "select your seat": "Sélectionnez votre siège",
  available: "Disponible",
  reserved: "Réservé",
  selected: "Sélectionné",
  vip: "VIP",
  "vip section": "SECTION VIP (prix x1.5)",
  "standard section": "SECTION STANDARD",
  "seats selected": "Sièges sélectionnés",
  "confirm booking": "Confirmer la réservation",
  "buses available": "Bus disponibles",
  "main terminal": "Terminal principal",
  "central station": "Gare centrale",
  "select seat": "Sélectionner un siège",
  "no buses found": "Aucun bus trouvé pour cet itinéraire à cette date.",
  "try another route": "Essayez un autre itinéraire",
  "my transactions": "Mes transactions",
  "total wallet activity": "Activité totale du portefeuille",
  "review spending": "Consultez vos dépenses et recharges récentes",
  "total in": "Total entrant",
  "total out": "Total sortant",
  "filter by month": "Filtrer par mois",
  "view all": "Voir tout",
  "no transactions found": "Aucune transaction trouvée.",
  "failed to load transactions": "Impossible de charger les transactions. Veuillez vérifier votre connexion.",
  "confirm payment": "Confirmer le paiement",
  "order summary": "Résumé de la commande",
  subtotal: "Sous-total",
  "medicine service fee": "Frais de service des médicaments",
  "paying with gahungu wallet": "Paiement avec Gahungu Wallet",
  "confirm and pay": "Confirmer et payer",
  "enter wallet pin": "Entrez le code PIN du portefeuille",
  "enter pin message": "Veuillez entrer votre code PIN à 4 chiffres pour confirmer le paiement.",
  "verify and pay": "Vérifier et payer",
  "travel with comfort": "Voyagez confortablement",
  "safe and reliable journeys": "Voyages sûrs et fiables dans toute la région",
  "popular routes": "Itinéraires populaires",
  from: "De",
  to: "À",
  "origin city": "Ville d'origine",
  "destination city": "Ville de destination",
  "departure date": "Date de départ",
  "search buses": "Rechercher des bus",
  "why choose jk bus": "Pourquoi choisir JK BUS ?",
  "air conditioned fleet": "• Flotte moderne climatisée",
  "experienced drivers": "• Conducteurs expérimentés et professionnels",
  "realtime gps tracking": "• Suivi GPS en temps réel pour la sécurité",
  "change pin": "Changer le PIN",
  "create pin": "Créer un PIN",
  "verify current pin": "Vérifiez votre PIN actuel",
  "enter current pin message": "Veuillez entrer votre code PIN actuel à 4 chiffres pour continuer.",
  "current pin": "PIN actuel",
  "verify pin": "Vérifier le PIN",
  "set new pin": "Définissez votre nouveau PIN",
  "set transaction pin": "Définir le PIN de transaction",
  "pin authorization message": "Ce code PIN à 4 chiffres sera utilisé pour autoriser vos paiements.",
  "new pin": "Nouveau PIN (4 chiffres)",
  "confirm new pin": "Confirmer le nouveau PIN",
  update: "Mettre à jour",
  "save pin": "Enregistrer le PIN",
  "app reviews": "Avis sur l'application",
  "total reviews": "avis au total",
  "highly recommended": "Fortement recommandé par les utilisateurs",
  "trusted companion": "Compagnon de santé fiable",
  "your name": "Votre nom",
  "tap to rate": "Touchez pour noter :",
  "gahungu team": "Équipe Gahungu",
  "failed to load reviews": "Impossible de charger les avis. Veuillez vérifier votre connexion.",
  "my engagement points": "Mes points d'engagement",
  "monetization goal": "Objectif de monétisation",
  threshold: "Seuil :",
  "points to reach goal": "EP pour atteindre votre objectif ! Continuez ainsi ! 💪",
  "goal reached": "Félicitations ! Vous avez atteint votre objectif de monétisation ! 🎉",
  "monetization info": "Remarque : après avoir atteint {monetizationGoal.toLocaleString()} EP, vous pourrez transformer vos points en argent et les retirer.",
  "daily summary": "Résumé quotidien",
  "posts liked today": "• Publications aimées aujourd'hui :",
  "stories viewed today": "• Stories vues aujourd'hui :",
  "points earned today": "• Points gagnés aujourd'hui :",
  "keep it up message": "Continuez ainsi cher utilisateur, notre équipe vous adore !!",
  "secure access fee": "Frais d'accès sécurisé",
  "access fee message": "Pour garantir le meilleur service, de petits frais d'accès sont requis pour continuer.",
  "access fee": "Frais d'accès",
  "gahungu wallet": "Gahungu Wallet",
  "available balance": "Solde disponible",
  "default pin notice": "Avis : votre PIN par défaut est 1616. Veuillez le modifier pour continuer.",
  "fee support message": "Ces frais soutiennent la maintenance du réseau de pharmacies Dr. Gahungu et sa disponibilité 24h/24 et 7j/7.",
  "default pin warning": "PIN par défaut : 1616. Changez-le maintenant !",
  "change pin to continue": "Changez le PIN pour continuer",
  "update pin": "Mettre à jour le PIN",
  "pay and enter app": "Payer et entrer dans l'application",
  "retry connection": "Réessayer la connexion",
  "wallet security": "Sécurité du Wallet",
  "enter pin to pay": "Entrez le PIN pour autoriser le paiement",
  "enter pin to show balance": "Entrez le PIN pour afficher le solde",
  "forgot pin": "PIN oublié ?",
  verify: "Vérifier",
  "no data": "Aucune donnée disponible",
  "no transactions to export": "Aucune transaction à exporter.",
  "transaction report": "Rapport de transactions",
  filter: "Filtrer",
  description: "Description",
  amount: "Montant",
  "generated by app on": "Généré par l'application le",
  error: "Une erreur s'est produite lors de la génération du PDF.",
  "failed to generate pdf": "Échec de la génération du PDF.",
  "wallet activity subtext": "Voici un résumé de votre activité récente dans Gahungu Wallet.",
  "contact admin": "Contacter l'administrateur",
  "contact admin whatsapp": "Voulez-vous ouvrir WhatsApp pour contacter l'administrateur au +25777990118 ?",
  "my cart": "Mon panier",
  "cart empty": "Votre panier est vide !",
  "browse products": "PARCOURIR LES PRODUITS",
  "choose payment method": "Choisissez le mode de paiement",
  "bank payment": "Paiement bancaire",
  "gahungu wallet balance": "Solde Gahungu Wallet",
  "proceed to payment": "Procéder au paiement",
  "failed to load wallet data": "Impossible de charger les données du Wallet. Veuillez vérifier votre connexion.",
  ep: "EP",
  "link to website": "Lien vers le site web",
  "click to whatsapp": "Cliquez ici pour WhatsApp",
  "follow on instagram": "Suivez-les sur Instagram",
  "follow on x": "Suivez-les sur X",
  likes: "mentions j'aime",
  "check out more here": "Découvrez-en plus ici",
  viewed: "Vu",
  "ep eligible message": "Votre EP actuel est de {engagementPoints.toLocaleString()}, vous êtes éligible pour réserver.",
  "ep warning message": "Votre EP actuel est inférieur à {minEpRequired.toLocaleString()}.",
  "earn ep message": "Cliquez ici pour augmenter vos EP en regardant des stories, en consultant des publications et en aimant des publications.",
  "customer support": "Support client",
  email: "E-mail",
  phone: "Téléphone",
  facebook: "Facebook",
  instagram: "Instagram",
  "terms and conditions": "Conditions générales",
  "last updated": "Dernière mise à jour : 2026",
  "terms introduction": "1. Introduction",
  "terms intro paragraph": "Bienvenue sur GAHUNGU PHARMACY (« Application », « nous », « notre »). En téléchargeant, accédant ou utilisant notre application mobile, vous acceptez d'être lié par ces Conditions générales. Si vous n'êtes pas d'accord, veuillez ne pas utiliser l'application.",
  "terms medical disclaimer": "2. Clause de non-responsabilité médicale",
  "terms medical disclaimer paragraph": "Consultez toujours votre médecin ou un autre professionnel de santé qualifié pour toute question concernant un problème médical. Ne négligez jamais les conseils médicaux professionnels et ne retardez jamais leur consultation à cause d'informations lues sur cette application. Toute confiance accordée aux informations fournies par l'application est à vos propres risques.",
  "terms user accounts": "3. Comptes utilisateurs",
  "terms user accounts paragraph": "Pour accéder à certaines fonctionnalités, vous devez créer un compte. Vous acceptez de fournir des informations exactes, actuelles et complètes lors de l'inscription et de les maintenir à jour. Vous êtes responsable de la sécurité de votre mot de passe et des activités effectuées sous votre compte.",
  "terms use of services": "4. Utilisation des services",
  "terms use of services paragraph": "Vous pouvez utiliser l'application uniquement à des fins légales. Vous acceptez de ne pas utiliser l'application pour :\n- Acheter des médicaments sur ordonnance sans ordonnance valide.\n- Violer une loi locale, nationale ou internationale.\n- Transmettre du contenu diffamatoire, offensant ou inapproprié.",
  "terms purchases and payments": "5. Achats et paiements",
  "terms purchases and payments paragraph": "Si vous souhaitez acheter un produit ou un service via l'application, certaines informations liées à votre achat pourront vous être demandées. Tous les paiements effectués via le portefeuille Gahungu sont soumis aux conditions de nos partenaires de paiement. Nous ne sommes pas responsables des erreurs ou problèmes liés au processus de paiement.",
  "terms privacy": "6. Confidentialité",
  "terms privacy paragraph": "Votre vie privée est importante pour nous. Notre politique de confidentialité explique comment nous collectons, utilisons et partageons vos informations personnelles. En utilisant cette application, vous acceptez cette collecte et utilisation des informations conformément à notre politique de confidentialité.",
  "terms limitation of liability": "7. Limitation de responsabilité",
  "terms limitation of liability paragraph": "En aucun cas GAHUNGU PHARMACY, ses directeurs, employés, partenaires ou agents ne pourront être tenus responsables des dommages indirects, accidentels, spéciaux ou consécutifs, y compris la perte de profits, de données ou de clientèle résultant de votre accès ou incapacité à utiliser l'application.",
  "terms changes to terms": "8. Modifications des conditions",
  "terms changes to terms paragraph": "Nous nous réservons le droit, à notre seule discrétion, de modifier ou remplacer ces Conditions à tout moment. Nous informerons les utilisateurs de tout changement en publiant les nouvelles Conditions générales sur cette page.",
  "terms contact us": "9. Contactez-nous",
  "terms contact us paragraph": "Si vous avez des questions concernant ces Conditions, veuillez nous contacter à supportgahungupharmacy@gmail.com.",
  "no medicines found for this category": "Nta muti wabonetse kuri iyi category",
  "medicines for": "Médicaments pour",
  "insurance not found": "Assurance non trouvée.",
  "standard plan": "Plan standard",
  "no plan details available": "Aucun détail de plan disponible.",
  "no office locations available": "Aucun emplacement de bureau disponible.",
  "no contact details available": "Aucune coordonnée disponible.",
  "leave app email message": "Vous pouvez quitter l'application pour envoyer un e-mail. Voulez-vous continuer ?",
  "leave app website message": "Vous allez quitter l'application pour visiter ce site Web. Voulez-vous continuer ?",
  office: "Bureau",
  web: "Web",
  "leave app":"Quitter l'application",
  "open whatsapp":"Ouvrir whatsapp",
  "you are about to leave the app to open Google Maps. do you want to continue?": "Vous êtes sur le point de quitter l'application pour ouvrir Google Maps. Voulez-vous continuer?",
  "open google maps": "Ouvrir Google Maps",
  "fill all fields": "Please fill in all fields.",
  "auth error": "Erreur d'authentication. Veuillez vous reconnecter.",
  "login to review": "Veuillez vous connecter pour écrire un avis.",
  "review updated": "Avis mis à jour",
  "changes saved": "Modifications enregistrées",
  "thanks feedback": "Merci pour votre avis !",
  "failed submit review": "Echec de donner l'avis. Veuillez vérifier votre connexion.",
  "failed update review": "Echec de mettre à jour l'avis. Veuillez vérifier votre connexion.",
  "failed delete review": "Echec de supprimer l'avis. Veuillez vérifier votre connexion.",
  "something went wrong": "Quelque chose s'est mal passé. Veuillez vérifier votre connexion.",
  "confirm delete review": "Êtes-vous sûr de vouloir supprimer votre avis ?",
  "review deleted": "Avis supprimé",
  delete: "Supprimer",
  "pin updated": "Code PIN mis à jour avec succès !",
  "connection error": "Erreur de connexion. Veuillez vérifier votre connexion internet et réessayer.",
  "your comment": "Votre commentaire",
  "support intro": "Vous avez des questions ou besoin d'aide pour votre commande ? Contactez-nous via l'un des canaux ci-dessous.",
  "leave app whatsapp message": "Vous êtes sur le point de quitter l'application pour ouvrir WhatsApp. Voulez-vous continuer ?",
  "cannot open url": "Impossible d'ouvrir cette URL :",
  "default pin alert message": "Votre code PIN est actuellement \"1616\" (par défaut). Pour votre sécurité, vous devez le modifier avant de pouvoir payer les frais d'accès.",
  "welcome message": "Bienvenue chez GAHUNGU PHARMACY",
  "whatsapp hint": "Commencez par le code pays comme: +25777990118",
  "enter whatsapp": "Entrez votre numéro WhatsApp",
  "whatsapp required": "Le numéro WhatsApp est requis.",
  "password hint": "Entrez votre code secret",
  "enter password": "Entrez votre mot de passe",
  "password required": "Le mot de passe est requis.",
  "country hint": "Sélectionnez le pays où vous souhaitez effectuer vos recherches",
  "country required": "Veuillez sélectionner un pays.",
  "login": "Se connecter",
  "forgot password": "Mot de passe oublié ?",
  "dont have account": "Vous n'avez pas de compte ? ",
  "register": "S'inscrire",
  "login error": "Erreur de connexion",
  "invalid response": "Réponse du serveur invalide. Consultez les logs.",
  "login failed alert": "Échec de la connexion ❌",
  "create account": "Créer un compte",
  "registration welcome": "Bienvenue chez le Dr. Gahungu, vous êtes déjà guéri !",
  "fullname hint": "Entrez votre nom comme : GAHUNGU",
  "fullname required": "Le nom complet est requis.",
  "password": "Mot de passe",
  "password hint long": "Lettres et chiffres, au moins 8 caractères. ex: Gahungu12345",
  "password must be at least 8 characters": "Le mot de passe doit contenir au moins 8 caractères.",
  "password must contain both letters and numbers": "Le mot de passe doit contenir des lettres et des chiffres.",
  "confirm password hint": "Répétez le mot de passe que vous venez de saisir",
  "confirm password required": "Veuillez confirmer votre mot de passe.",
  "passwords dont match": "Les mots de passe ne correspondent pas.",
  "select country": "Sélectionnez votre pays",
  "search country": "Rechercher un pays...",
  "country hint long": "Cliquez et sélectionnez le pays où vous vous trouvez",
  "whatsapp format error": "Entrez un numéro valide avec le code pays (ex : +257...).",
  "whatsapp registered error": "Ce numéro WhatsApp est déjà enregistré.",
  "error checking whatsapp": "Erreur lors de la vérification du numéro WhatsApp.",
  "checking whatsapp": "Vérification du numéro WhatsApp...",
  "secret question label": "Quelle partie de votre corps aimez-vous le plus ? Retenez-le !!",
  "select answer": "Sélectionnez une réponse",
  "secret answer required": "Veuillez répondre à la question secrète.",
  "male": "Homme",
  "female": "Femme",
  "terms agree start": "En cochant cette case, vous acceptez les",
  "confirm details title": "Confirmez vos informations",
  "confirm details message": "Ces informations sont-elles correctes ?",
  "registered alert title": "Inscription réussie ✅",
  "registered alert message": "Vous pouvez maintenant vous connecter !",
  "registration failed": "Échec de l'inscription ❌",
  head: "Tête",
  legs: "Jambes",
  lips: "Lèvres",
  body: "Corps",
  eyes: "Yeux",
  fingers: "Doigts",
  "secret answer": "Réponse secrète",
  "confirm password": "Confirmer le mot de passe",
  country: "Pays actuel",
  "insufficient engagement points": "Points d'engagement insuffisants",
  "ep required to book message": "Vous avez besoin de {minEpRequired} EP pour réserver. Gagnez-en plus en regardant des stories, des publications et en aimant le contenu !",
  "authentication error": "Erreur d'authentification",
  "wallet error": "Erreur du wallet",
  "failed to fetch balance": "Échec de la récupération du solde.",
  "insufficient balance": "Solde insuffisant",
  "please add funds to wallet": "Veuillez ajouter des fonds à votre wallet.",
  "failed to verify wallet balance": "Échec de la vérification du solde du wallet.",
  "invalid pin": "Code PIN invalide",
  "please enter 4-digit pin": "Veuillez entrer un code PIN à 4 chiffres.",
  "booking confirmed": "Réservation confirmée 🎉",
  "reserved seats message": "Réservé {seatsLength} sièges pour votre voyage !",
  "booking failed": "Échec de la réservation",
  "something went wrong booking": "Une erreur s'est produite lors de la réservation de votre siège.",
  "not available": "N/A",
  "seats": "Sièges",
  "seat price": "Prix du siège",
  "bus service fee": "Frais de service de bus",
  "pay from gahungu wallet": "Payer avec wallet Gahungu",
  "checking eligibility": "Vérification de votre éligibilité...",
  "eligible to book message": "Votre EP actuel est de {engagementPoints}, vous êtes éligible pour réserver.",
  "ep less than required message": "Votre EP actuel est inférieur aux {minEpRequired} requis.",
  "earn ep by engaging": "Cliquez ici pour augmenter votre EP en regardant des stories, des publications et en aimant les publications.",
  "enter pin": "Entrez le code PIN",
  "dashboardOverview": "Aperçu du tableau de bord",
  "loadingStats": "Chargement des statistiques...",
  "totalCustomers": "Total Clients",
  "totalProducts": "Total Produits",
  "totalRevenue": "Revenu Total",
  "totalPendingOrders": "Commandes en attente",
  "totalViews": "Vues Totales",
  "withdraw": "Retirer",
  "withdrawSoon": "L'équipe est en train de l'implémenter pour bientôt",
  "revenueLast7Days": "Revenu (7 derniers jours)",
  "ordersLast7Days": "Commandes (7 derniers jours)",
  "profileViewsLast7Days": "Vues du profil (7 derniers jours)",
  "recentActivity": "Activité récente",
  "orderId": "ID Commande",
  "noRecentOrders": "Aucune commande récente",
  "welcomeGreeting": "Salutations et bienvenue cher",
  "welcomeGreetingSuffix": "sur la plateforme Dr. Gahungu.",
  "myStock": "Mon Stock",
  "orders": "Commandes",
  "myPharmacy": "Ma pharmacie",
  "getApprovedFirst": "Vous devez être approuvé d'abord",
  "updatePasswordFail": "Échec de la mise à jour du mot de passe",
  "updatePasswordSuccess": "Mot de passe mis à jour avec succès",
  "underReview": "En cours d'examen",
  "pendingStatusMessage": "Votre demande est actuellement examinée par notre équipe.",
  "approved": "Approuvé",
  "loadingForm": "Chargement du formulaire...",
  "editResubmitApp": "Modifier et soumettre à nouveau la demande",
  "stockManagement": "Gestion de mon stock",
  "editItem": "Modifier l'article",
  "addNewItem": "Ajouter un nouvel article",
  "itemName": "Nom de l'article",
  "originalPrice": "Prix d'origine",
  "quantity": "Quantité",
  "selectCategory": "Sélectionner une catégorie",
  "applicableInsurances": "Assurances applicables",
  "uploadImage": "Télécharger une image",
  "changeImage": "Changer l'image",
  "updateItem": "Mettre à jour l'article",
  "addItem": "Ajouter un article",
  "saving": "Enregistrement...",
  "searchItemsPlaceholder": "Rechercher des articles...",
  "noItemsInStock": "Aucun article en stock",
  "noItemsMatchSearch": "Aucun article ne correspond à votre recherche",
  "inStock": "En Stock",
  "outOfStock": "Rupture de stock",
  "incomingOrders": "Commandes entrantes",
  "customer": "Client",
  "viewItems": "Voir les articles",
  "printInvoice": "Imprimer la facture",
  "noBookingsFound": "Aucune commande trouvée",
  "openingHoursLabel": "Heures d'ouverture",
  "hours24": "24 Heures",
  "payment summary": "Résumé du paiement",
  "change PIN":"PIN actuel est correct. Vous pouvez maintenant modifier votre PIN",
  "pin mismatch":"Les PIN ne correspondent pas. Veuillez réessayer.",
  "failed to update pin":"Échec de la mise à jour du PIN. Veuillez vérifier votre connexion.",
  "pin must":"PIN doit avoir 4 chiffres. Veuillez réessayer.",
  "confirm update": "Confirmer la mise à jour",
  "update profile logout message": "La mise à jour de votre profil vous déconnectera automatiquement. Voulez-vous continuer ?",
  "profile updated success message": "Profil mis à jour avec succès ! Pour des raisons de sécurité, vous allez maintenant être déconnecté. Veuillez vous reconnecter avec vos identifiants mis à jour.",
  "leave app facebook message": "Vous allez quitter l'application pour visiter Facebook. Voulez-vous continuer ?",
  "leave app instagram message": "Vous allez quitter l'application pour visiter Instagram. Voulez-vous continuer ?",
  "leave app twitter message": "Vous allez quitter l'application pour visiter X. Voulez-vous continuer ?",
  "missing order details": "Détails de la commande manquants.",
  "unexpected server response": "Réponse inattendue du serveur.",
  "order failed": "Échec de la commande",
  "failed create order": "Échec de la création de la commande. Veuillez réessayer.",
  "payment failed": "Échec du paiement",
  "please try again": "Veuillez réessayer.",
  "order placed message": "Votre commande {orderId} a été passée !",
  "order details": "Détails de la commande",
  "items": "Articles",
  "item": "Article",
  "sold by": "Vendu par :",
  "status": "Statut :",
  "no items found": "Aucun article trouvé dans cette commande.",
  "order confirmation": "Confirmation de la commande",
  "qr verification help": "Présentez ce code QR à la pharmacie pour vérification.",
  "download invoice": "Télécharger la facture",
  "order not found": "Commande introuvable",
  "order details not found": "Les détails de la commande n'ont pas pu être trouvés.",
  "wallet payment maintenance": "Le Dr. IR. Gahungu y travaille, bientôt disponible !",
  "create username": "Créer un nom d'utilisateur",
  "add a comment": "Ajouter un commentaire",
  "commenting as": "Commentaire en tant que",
  "on post": "Sur la publication",
  "create username title": "Créer un nom d'utilisateur",
  "create username message": "Votre nom d'utilisateur doit être unique et contenir entre 3 et 15 caractères. Il peut inclure des lettres, des chiffres et des underscores (_). Veuillez choisir un nom d'utilisateur qui vous représente !",
  "card maintenance": "Les paiements par carte sont actuellement en maintenance.",
  "comment submitted message": "Votre commentaire a été publié !",
  "failed to update username": "Échec de la mise à jour du nom d'utilisateur.",
  "enter username": "Entrez le nom d'utilisateur souhaité",
  "failed to submit comment": "Commentaire non Soumis",
  "notifications": "Notifications",
  "no notifications yet": "Aucune notification pour le moment.",
  "mentioned you in a comment": "vous a mentionné dans un commentaire",
  "replied to your comment": "a répondu à votre commentaire",
  "comment submitted":"Commentaire Soumis",
  "edit your application": "Modifier votre demande",
  "welcome doctor application": "Bienvenue Docteur",
  "needs attention": "Votre demande nécessite une attention particulière",
  "rejection reason label": "Motif du rejet :",
  "rejection instructions": "Veuillez revoir vos informations, apporter les modifications nécessaires et soumettre à nouveau votre demande.",
  "specialty": "Spécialité",
  "country of origin": "Pays d'origine",
  "bio": "Bio",
  "bio placeholder": "Une brève biographie du docteur...",
  "payment id": "ID de paiement",
  "payment id placeholder": "Votre ID de paiement",
  "whatsapp hint doctor": "Commencez par le code pays comme +12345678",
  "password placeholder doctor": "Créez un mot de passe",
  "doctor image": "Image du docteur",
  "choose image": "Choisir une image",
  "doctor terms": "J'accepte par la présente les conditions générales du Dr Gahungu.",
  "resubmit form": "Renvoyer le formulaire",
  "submit form": "Soumettre le formulaire",
  "application updated success": "Demande mise à jour avec succès ! Nous l'examinerons prochainement.",
  "application submitted success": "Demande soumise avec succès ! Connectez-vous pour vérifier votre statut.",
  "submitting": "Envoi en cours...",
  "passwordsMatchError": "Les nouveaux mots de passe ne correspondent pas",
  "incorrectCurrentPassword": "Mot de passe actuel incorrect",
  "enterCurrentPassword": "Veuillez entrer votre mot de passe actuel",
  "passwordTooShort": "Le nouveau mot de passe doit comporter au moins 6 caractères",
  "updatePasswordError": "Une erreur est survenue lors de la mise à jour du mot de passe",
  timesCommaSeparated: "Heures (séparées par des virgules)",
  bookingType: "Type de réservation",
  onlineFee: "Frais en ligne",
  officeFee: "Frais au cabinet",
  remove: "Supprimer",
  day: "Jour",
  start: "Début",
  end: "Fin",
  breakStart: "Début de pause",
  breakEnd: "Fin de pause",
  inOffice: "Au cabinet",
  both: "Les deux",
  fee: "Frais",
},
  rn: {
  "failed to update profile": "Vyanse guhindura amakuru yawe. Raba ko ufise internet.",
  "failed to load profile": "Vyanse kuronka amakuru yawe. Raba ko ufise internet.",
  "write your comment here...": "Andika komantere yawe hano...",
  username: "Username",
  "username required": "Username irakenewe.",
  "username format error": "Username itegerezwa kuba hagati y'inyuguti 3 na 15 kandi rishobora kuba ririmwo gusa inyuguti, imibare, n'akarongo ko hasi (_).",
  "login to continue": "Injira kugira ngo ukomeze.",
  "success": "Vyagenze neza",
  "username updated success": "Username yahinduwe neza!",
  "create username message": "Banza ukore agatazirana imbere yuko ugira komantere",
  "comment submitted message": "Komantere yemejwe",
  "failed to submit comment": "Komantere ntiyemejwe",
  "comment submitted":"Komantere yemejwe",
  settings: "Amagenamiterere",
  logout: "Gusohoka",
  confirmLogout: "Kwemeza gusohoka",
  logoutMessage: "Woba ushaka gusohoka?",
  cancel: "Kureka",
  language: "Ururimi",
  dataCountry: "Igihugu c'amakuru",
  home: "Ahabanza",
  cart: "Agaseke",
  profile: "Jewe",
  "murahawe ikaze kuri MELANA:": "Murahawe Ikaze kuri MELANA:",
  doctors: "Abadogiteri",
  "no medicines found for this category": "Nta muti wabonetse kuri iyi category",
  pharmacies: "Pharumacies",
  hospitals: "Ibitaro",
  insurances: "Ubwishingizi",
  explore: "Ibigezweho",
  categories: "Amacategories",
  "please check your internet connection and try again": "Raba ko ufise internet hanyuma usubireko",
  "all categories": "Amacategories yose",
  "deals of the day": "Amadili yuno musi",
  "recommended for you": "Utubonetse hafi",
  "featured pharmacies": "Amapharumacie dukorana",
  "featured hospitals": "Ibitaro dukorana",
  "featured insurances": "Ubwishingizi dukorana",
  "featured doctors": "Abadogiteri dukorana",
  "no hospitals available": "Nta bitaro bihari",
  "no products available": "Nta bicuruzwa bihari",
  "no doctors available": "Nta badogiteri bahari",
  "no insurances available": "Nta bwishingizi buhari",
  "no pharmacies available": "Nta mapharumacie ahari",
  "no deals available": "Nta madili yuno musi ahari",
  "unknown doctor": "Uyu mudogiteri ntazwi",
  confirmed: "Yemejwe",
  cancelled: "Yahagaritswe",
  pending: "Iriko irakorwa",
  "ticket number": "Nomero ya tike",
  "online consultation": "Kuganira na muganga kuri internet",
  "in-office visit": "Kuganira na muganga mu biro",
  "with melana": "na porogaramu ya Melana",
  complete: "Vyuzuye",
  incomplete: "Ntivyuzuye",
  refunded: "Vyasubijwe",
  paid: "Vyishuwe",
  "failed to load appointments": "Kubura amaporogamu. Raba ko ufise internet.",
  "no appointments found": "Nta porogamu zabonetse.",
  "no data": "Nta makuru aboneka",
  "no transactions to export": "Nta vyakozwe bihari",
  "transaction report": "Raporo y'ivyakozwe",
  "all transactions": "Ivyakozwe vyose",
  filter: "Hitamwo",
  description: "Ibisobanuro",
  amount: "Amafaranga",
  "generated by app on": "Vyakozwe na porogaramu kuwa",
  error: "Ikosa ryabaye.",
  "failed to generate pdf": "Kubura PDF. Raba ko ufise internet.",
  "wallet activity subtext": "Raba uko wakoresheje amafaranga yawe",
  "product details": "Ibirango vy'igicuruzwa",
  "add to cart": "Shira mu gaseke",
  "added to cart": "Vyashizwe mu gaseke",
  "go to cart": "Ja mu gaseke",
  "out of stock": "Ntikiri muri stock",
  "available at": "Biboneka kuri",
  locations: "Ikibanza",
  contact: "Kuturonka",
  price: "Igiciro",
  "view on map": "Raba ku karata",
  "opening hours": "Amasaha yo kwugurura",
  closed: "Vyuga",
  reviews: "Ivyiyumviro",
  yes: "Ego",
  no: "Oya",
  "call car": "Hamagara umuduga",
  "no reviews yet": "Nta vyiyumviro biraboneka",
  "write a review": "Andika iciyumviro",
  submit: "Rungika",
  "your review": "Iciyumviro cawe",
  "thank you for your review": "Urakoze ku ciyumviro cawe",
  "review submitted": "Iciyumviro carungitswe",
  "review submission failed": "Kurungika iciyumviro vyanse",
  "edit review": "Hindura iciyumviro",
  "doctor not found": "Dogiteri ntiyabonetse.",
  "hospital not found": "Ibitaro ntivyabonetse.",
  "delete review": "Gufuta iciyumviro",
  "my appointments": "Imibonano yanje",
  "orders description": "Raba aho ivyo watumye bigeze",
  "appointments description": "Raba imibonano ufise n'abaganga",
  "transactions description": "Raba uko wakoresheje amafaranga",
  "bus booking description": "Genda neza kandi wisanzuye",
  "bus tickets description": "Raba amatike yawe yafashwe",
  "reviews description": "Raba ivyo abandi bavuga kuri app",
  "pin description": "Gukora canke guhindura PIN yo kuriha",
  "support description": "Gahungu arahimbawe no kugufasha",
  "update profile description": "Guhindura amakuru yawe",
  "settings description": "Amagenamiterere ya app",
  mon: "KUWA 1",
  tue: "KUWA 2",
  wed: "KUWA 3",
  thu: "KUWA 4",
  fri: "KUWA 5",
  sat: "KUWA 6",
  sun: "KUWA 7",
  "accepted insurances": "Ubwishingizi bwemewe",
  "insurance details": "Insiguro z'ubwishingizi",
  coverage: "Ivyishingiwe",
  "contact details": "Uko mwoturonka",
  "pharmacy details": "Details za pharmacie",
  "hospital details": "Details z'ibitaro",
  "no doctors found":"Nta badogiteri babonetse",
  "service summary": "Incamake ya seruvisi",
  "admission process": "Uburyo bwo kwakirwa",
  "available services": "Seruvisi ziboneka",
  "available blood types": "Amaraso aboneka",
  "medical equipment": "Ibikoresho vy'ubuvuzi",
  "Partner Pharmacies": "Amapharumacie dukorana",
  "main location": "Ikibanza gikuru",
  "open in google maps": "Ugurura muri Google Maps",
  "doctor profile": "Umwirondoro wa dogiteri",
  about: "Ibimugize",
  "working hours": "Amasaha y'akazi",
  "availability & booking": "Kuboneka no ku bookinga",
  "available times": "Amasaha aboneka",
  "book online": "Bookinga kuri internet",
  "book in-office": "Bookinga mu biro",
  "view my transactions": "Raba ivyo wakoresheje",
  "transaction pin": "PIN yo kuriha",
  version: "Version",
  "book an appointment": "Ku bookinga umubonano",
  "appointment booked": "Umubonano wabookinzwe",
  "appointment booking failed": "Kubookinga umubonano vyanse",
  "see details": "Raba ama details",
  "insurance type": "Ubwishingizi buhari",
  "coverage summary": "Incamake y'uko bukora",
  "claim process": "Uburyo bwo kwishuza",
  "partner hospitals": "Ibitaro dukorana",
  "partner pharmacies": "Amapharumacie dukorana",
  "office locations": "Ahari ibiro",
  "branch office": "Ishami",
  "all doctors": "Abadogiteri bose",
  "pay and book": "Riha uheze ubookinge",
  "payment successful": "Kuriha vyagenze neza!",
  "redirecting to appointments": "Turiko tukujana ahabereye...",
  "insufficient wallet balance": "Amafaranga afise muri wallet ntahagije.",
  "please log in to book": "Banza winjire (login) kugira ubookinge.",
  "duplicate booking message": "Usanganywe iyindi booking na uyu muganga kuri iyi saha.",
  "failed to check existing bookings": "Ntivyashobotse kuraba izindi booking ufise.",
  "incorrect pin": "PIN siyo.",
  "no image available": "Nta shusho ihari",
  "all pharmacies": "Amapharumacie yose",
  "all hospitals": "Ibitaro byose",
  "all insurances": "Ubwishingizi bwose",
  searchPlaceholder: "Rondera imiti, abaganga, ibitaro, ...",
  searchPlaceholderText: "Ronderera hano na Gahungu Search...",
  "no results found for": "Nta nyishu yabonetse kuri",
  "try different keywords": "Gerageza ayandi majambo",
  "searching for": "Turiko turondera",
  "results for": "Inyishu za",
  "recent searches": "Ivyo uheruka kurondera",
  "clear all": "Futa vyose",
  "type to see suggestions": "Andika inyuguti 2 canke zirenga kugira ubone ivyiyumviro",
  "my prescriptions": "Impapuro zanje z'imiti",
  "covered by": "Vyishingiwe na:",
  "no prescriptions found": "Nta mpapuro z'imiti zabonetse.",
  "try different spellings": "Gerageza ayandi majambo.",
  payment: "Kuriha",
  "booking details": "Details za booking",
  doctor: "Dogiteri",
  date: "Itariki",
  time: "Isaha",
  type: "Ikibanza",
  online: "Kuri internet",
  "in-office": "Mu biro",
  "consultation fee": "Amafaranga yo kubonana na dogiteri",
  "doctor service fee": "Amafaranga ya serivisi ya dogiteri",
  "total amount": "Amafaranga yose",
  "payment method": "Uburyo bwo kuriha",
  "pay with gahungu wallet": "Riha ukoresheje Gahungu Wallet",
  "pay with gahungu card": "Riha ukoresheje ikarata ya Gahungu",
  "my orders": "Ivyo natumye",
  "order hash": "Commande #",
  "placed on": "Vyatumwe kuwa:",
  total: "Vyose hamwe:",
  "check order status": "Raba aho ivyo watumye bigeze",
  "no orders yet": "Nta vyo uratuma.",
  "start shopping": "Tanguragu shoppinga",
  "failed to load orders": "Ntivyashobotse gutora ivyo watumye. Raba internet.",
  retry: "Subiramwo",
  "update profile": "Hindura umwirondoro",
  "full name": "Amazina yose",
  "whatsapp number": "Numero ya WhatsApp (akarorero +257...)",
  updating: "Biriko birahindurwa...",
  "save changes": "Emeza amahinduka",
  "my bus tickets": "Amatike yanje ya bisi",
  new: "GISHASHA",
  origin: "Aho uva",
  destination: "Aho uja",
  seat: "Intebe",
  id: "ID:",
  "scan at boarding": "Scanna igihe winjira",
  service: "Seruvisi",
  "no tickets yet": "Nta matike uragira.",
  "book a jk bus": "Fata JK BUS",
  "failed to load bus tickets": "Ntivyashobotse gutora amatike. Raba internet.",
  "select your seat": "Hitamwo intebe yawe",
  available: "Irahari",
  reserved: "Yafashwe",
  selected: "Yatoranijwe",
  vip: "VIP",
  "vip section": "IGICE CA VIP (igiciro x1.5)",
  "standard section": "IGICE GISANZWE",
  "seats selected": "Intebe zafashwe",
  "confirm booking": "Emeza",
  "buses available": "Amabisi ahari",
  "main terminal": "Terminal nyamukuru",
  "central station": "Gare nkuru",
  "select seat": "Hitamwo intebe",
  "no buses found": "Nta bisi yabonetse kuri uru rugendo.",
  "try another route": "Gerageza urundi rugendo",
  "my transactions": "Uko amafaranga yanje yakoreshejwe",
  "total wallet activity": "Ibikorwa vyose vya wallet",
  "review spending": "Raba amafaranga wakoresheje n'ayo washizemwo",
  "total in": "Amafaranga yinjiye",
  "total out": "Amafaranga yasohotse",
  "filter by month": "Toranya ukwezi",
  "view all": "Raba vyose",
  "no transactions found": "Nta bikorwa vyabonetse.",
  "failed to load transactions": "Ntivyashobotse gutora ibikorwa vyawe.",
  "confirm payment": "Emeza ukuriha",
  "order summary": "Incamake y'ivyo watumye",
  subtotal: "Amafaranga",
  "medicine service fee": "Amafaranga ya seruvisi",
  "paying with gahungu wallet": "Kuriha ukoresheje Gahungu Wallet",
  "confirm and pay": "Emeza kandi urihe",
  "enter wallet pin": "Shiramwo PIN ya wallet",
  "enter pin message": "Shiramwo PIN yawe y'ibiharuro 4 kugira urihe.",
  "update pin": "Hindura PIN",
  "verify and pay": "Kuriha",
  "travel with comfort": "Genda neza kandi wisanzuye",
  "safe and reliable journeys": "Ingendo zizewe kandi zitekanye",
  "popular routes": "Ingendo zikunzwe",
  from: "Aho uvuye",
  to: "Aho uja",
  "origin city": "Hitamwo aho uva",
  "destination city": "Hitamwo aho uja",
  "departure date": "Itariki yo kugenda",
  "search buses": "Rondera amabisi",
  "why choose jk bus": "Kubera iki uhitamwo JK BUS?",
  "air conditioned fleet": "• Amabisi agezweho afise climatiseur",
  "experienced drivers": "• Abashoferi b'abahinga",
  "realtime gps tracking": "• GPS y'umutekano ikora igihe cose",
  "change pin": "Hindura PIN",
  "create pin": "Kora PIN",
  "verify current pin": "Emeza PIN yawe",
  "enter current pin message": "Shiramwo PIN yawe y'ibiharuro 4 kugira ubandanye.",
  "current pin": "PIN ukoresh ubu",
  "verify pin": "Emeza PIN",
  "set new pin": "Gukora PIN nshasha",
  "set transaction pin": "Gukora PIN yo kuriha",
  "pin authorization message": "Iyi PIN y'ibiharuro 4 izokoreshwa mu kwemeza ukuriha.",
  "new pin": "PIN nshasha (ibiharuro 4)",
  "confirm new pin": "Emeza PIN nshasha",
  "confirm password": "Subizamwo iyo Password",
  update: "Shira ku gihe",
  "save pin": "Bika PIN",
  "app reviews": "Ivyiyumviro kuri app",
  "total reviews": "Ivyiyumviro vyose",
  "highly recommended": "Ibiza imbere",
  "trusted companion": "Umugenzi wawe mu buzima",
  "your name": "Izina ryawe",
  "tap to rate": "Fyonda kugira utange amanota:",
  "gahungu team": "Team Gahungu",
  "failed to load reviews": "Ntivyashobotse kuzana ivyiyumviro.",
  "my engagement points": "Amanota yanje",
  "monetization goal": "Intumbero yo kuronka amafaranga",
  threshold: "Igipimo:",
  "points to reach goal": "EP zisigaye kugira ushikire intumbero yawe! Komera!",
  "goal reached": "Turagukeje! Washitse ku ntumbero yawe! 🎉",
  "monetization info": "Iyo ushikije {monetizationGoal.toLocaleString()} EP, uzoshobora kuyahindura amafaranga.",
  "daily summary": "Incamake y'umunsi",
  "posts liked today": "• Ama posts wakunze uno munsi:",
  "stories viewed today": "• Stories wabonye uno munsi:",
  "points earned today": "• Amanota waronse uno munsi:",
  "keep it up message": "Komera cane, team yacu iragukunda!!",
  "secure access fee": "Amafaranga yo kwinjira",
  "access fee message": "Kugira turonke seruvisi nziza, harasabwa amafaranga make yo kwinjira.",
  "access fee": "Amafaranga yo kwinjira:",
  "gahungu wallet": "Gahungu Wallet",
  "available balance": "Amafaranga ahari:",
  "default pin notice": "PIN ya mbere ni 1616. Hindura kugira ubandanye.",
  "fee support message": "Aya mafaranga afasha kubungabunga ibikorwa vya Dr. Gahungu.",
  "default pin warning": "PIN ya mbere: 1616. Yihindure ubu!",
  "change pin to continue": "Hindura PIN kugira ubandanye",
  "pay and enter app": "Riha uheze winjire muri app",
  "retry connection": "Subiramwo connexion",
  "wallet security": "Umutekano wa Wallet",
  "enter pin to pay": "Shiramwo PIN kugira wishure",
  "enter pin to show balance": "Shiramwo PIN kugira ubone amafaranga",
  "forgot pin": "Wibagiye PIN?",
  verify: "Emeza",
  "contact admin": "Vugana na admin",
  "contact admin whatsapp": "Woba ushaka gufungura WhatsApp kugira uvugane na admin kuri +25777990118?",
  "my cart": "Agaseke kanje",
  "cart empty": "Agaseke kawe karimwo ubusa!",
  "browse products": "RABA IBICURUZWA",
  "choose payment method": "Hitamwo uburyo bwo kuriha",
  "bank payment": "Kuriha biciye muri banki",
  "gahungu wallet balance": "Balance ya Gahungu Wallet",
  "proceed to payment": "Bandanya kuriha",
  "failed to load wallet data": "Ntivyashobotse gutora amakuru ya wallet.",
  ep: "EP",
  "link to website": "Link y'urubuga",
  "click to whatsapp": "Fyonda hano kuri WhatsApp",
  "follow on instagram": "Bafollowinge kuri Instagram",
  "follow on x": "Bafollowinge kuri X",
  likes: "likes",
  "check out more here": "Raba vyinshi hano",
  viewed: "Vyabonwe",
  "ep eligible message": "EP zawe ni {engagementPoints.toLocaleString()}, urashoboye gufata réservation.",
  "ep warning message": "EP zawe ziri munsi ya {minEpRequired.toLocaleString()}.",
  "earn ep message": "Fyonda hano wongere EP mu kuraba stories no gukunda posts.",
  "customer support": "Ubufasha ku banywanyi",
  "Dieu avec Gahungu, Votre Santé est assurée": "Imana na Gahungu, Amagara yanyu ni meza 100%.",
  email: "Email",
  phone: "Telefone",
  facebook: "Facebook",
  instagram: "Instagram",
  "terms and conditions": "Amategeko n'amabwirizwa",
  "last updated": "Vyahinduwe bwa nyuma: 2026",
  "terms introduction": "1. Intangamarara",
  "terms intro paragraph": "Murakaza neza kuri GAHUNGU PHARMACY. Mu gukoresha iyi app, muremera aya mategeko n'amabwirizwa.",
  "terms medical disclaimer": "2. Inyishu ku bijanye n'ubuvuzi",
  "terms medical disclaimer paragraph": "Nimwame mwitura umuganga igihe mufise ikibazo c'amagara.",
  "terms user accounts": "3. Konti z'abakoresha",
  "terms user accounts paragraph": "Kugira mukoreshe zimwe muri seruvisi, mutegerezwa gukora konti.",
  "terms use of services": "4. Gukoresha seruvisi",
  "terms use of services paragraph": "Ntibirekuwe gukoresha app mu buryo bunyuranye n'amategeko.",
  "terms purchases and payments": "5. Kugura no kuriha",
  "terms purchases and payments paragraph": "Amafaranga yose yishurwa biciye muri Gahungu Wallet.",
  "terms privacy": "6. Privacy",
  "terms privacy paragraph": "Turubahiriza amakuru yanyu bwite.",
  "terms limitation of liability": "7. Kutaryozwa",
  "terms limitation of liability paragraph": "GAHUNGU PHARMACY ntizoryozwa ibibazo biturutse ku gukoresha app.",
  "terms changes to terms": "8. Guhindura amategeko",
  "terms changes to terms paragraph": "Turafise uburenganzira bwo guhindura aya mategeko igihe cose tubonye bikenewe.",
  "terms contact us": "9. Twandikire",
  "terms contact us paragraph": "Nimba mufise ikibazo, twandikire kuri supportgahungupharmacy@gmail.com.",
  "medicines for": "Umuti wa",
  "insurance not found": "Ubwishingizi ntiwaboneka.",
  "standard plan": "Uburyo busanzwe",
  "no plan details available": "Nta details z'uburyo zihari.",
  "no office locations available": "Nta biro bihari.",
  "no contact details available": "Nta kuntu wobashikira.",
  "leave app email message": "Ugira usohoke muri app kugira urungike email. Woba ushaka kubandanya?",
  "leave app website message": "Ugira usohoke muri app kugira urabe urubuga. Woba ushaka kubandanya?",
  office: "Ibiro",
  web: "Web",
  "leave app":"Gusohoka muri app",
  "open whatsapp":"Ugurura WhatsApp",
  "you are about to leave the app to open Google Maps. do you want to continue?": "Ugira usohoke application,Urakeneye kubandanya?",
  "open google maps": "Ugurura Google Maps",
  "fill all fields": "Uzuza amakuru yose.",
  "auth error": "Ikosa ry'authentication. Gerageza wongere winjire?",
  "login to review": "Injira kugira utange iciyumviro?",
  "review updated": "Iciyumviro cahinduwe",
  "changes saved": "Ivyahinduwe yabitswe",
  "thanks feedback": "Murakoze ku ciyumviro canyu!",
  "failed submit review": "Iciyumviro canyu ntibashoboye kurungikwa. Raba ko ufise internet.",
  "failed update review": "Iciyumviro canyu nticashoboye gushirwa ku gihe. Raba ko ufise internet.",
  "failed delete review": "Iciyumviro canyu ntibashoboye gufutwa. Raba ko ufise internet.",
  "something went wrong": "Hari icagenze nabi. Raba ko ufise internet.",
  "confirm delete review": "Woba ushaka gufuta iciyumviro cawe?",
  "review deleted": "Iciyumviro cafuswe",
  delete: "Futa",
  "pin updated": "PIN yahinduwe neza!",
  "connection error": "Ikosa rya interneti. Raba ko ufise internet.",
  "your comment": "Komantere yanyu",
  "support intro": "Ufise ibibazo canke ukeneye ubufasha ku vyo watumye? Twandikire kuri zimwe mu nzira ziri hano musi.",
  "leave app whatsapp message": "Ugira usohoke muri app kugira ufungure WhatsApp. Woba ushaka kubandanya?",
  "cannot open url": "Ntivyashobotse kwugurura iyi URL:",
  "default pin alert message": "PIN yawe ni \"1616\" (ya mbere). Ku bwo umutekano wawe, utegerezwa kuyihindura imbere yo kuriha amafaranga yo kwinjira.",
  "welcome message": "Murakaza neza kuri MELANA ya GAHUNGU",
  "whatsapp hint": "Tanguza kode y'Igihugu urimwo nkuku: +25777990118",
  "enter whatsapp": "Shiramwo numero yawe ya WhatsApp",
  "whatsapp required": "Numero ya WhatsApp irakenewe.",
  "password hint": "Shiramwo password yawe",
  "enter password": "Shiramwo password yawe",
  "password required": "Password irakenewe.",
  "country hint": "Cagura Igihugu ushaka kuzoronderamwo",
  "country required": "Cagura igihugu.",
  "login": "Injira",
  "forgot password": "Wibagiye code?",
  "dont have account": "Nta konti ufise? ",
  "register": "Iyandikishe",
  "login error": "Ikosa mu kwinjira",
  "invalid response": "Inyishu ya server ntiyagenze neza. Raba logs.",
  "login failed alert": "Kwinjira vyanse ❌",
  "create account": "Gukora konti",
  "registration welcome": "Murakaza neza kwa Dr. Gahungu, mwamaze gukira!",
  "fullname hint": "Shiramwo Izina ryawe nkuku: GAHUNGU",
  "fullname required": "Izina rirakenewe.",
  "password": "Password",
  "password hint long": "Indome nibiharuro kandi bikwire umunani nkuku: Gahungu12345",
  "password must be at least 8 characters": "Password itegerezwa kuba ifise inyuguti 8 canke zirenga.",
  "password must contain both letters and numbers": "Password itegerezwa kuba ifise indome nibiharuro.",
  "confirm password hint": "Subizamwo iyo Password waruhejeje gushiramwo",
  "confirm password required": "Emeza iyo Password yawe.",
  "passwords dont match": "Password ntizihuye.",
  "select country": "Cagura igihugu",
  "search country": "Rondera igihugu...",
  "country hint long": "Fyonda hama ucagure igihugu urimwo ubu",
  "whatsapp format error": "Tanguza kode y'Igihugu urimwo nkuku: +257...",
  "whatsapp registered error": "Iyi numero ya WhatsApp yaramaze kwiyandikisha.",
  "error checking whatsapp": "Habaye ikosa mu kuraba numero ya WhatsApp.",
  "checking whatsapp": "Turiko turaraba numero ya WhatsApp...",
  "secret question label": "Nikihe gihimba ukunda cane kuri wewe? Ugifate kumutwe!!",
  "select answer": "Cagura inyishu",
  "secret answer required": "Ishura ico kibazo c'ibanga.",
  "male": "Umugabo",
  "female": "Umugore",
  "terms agree start": "Fyonda muri kano ga case, hama uzoba wemeye",
  "confirm details title": "Emeza amakuru yawe",
  "confirm details message": "Aya makuru ni yo?",
  "registered alert title": "Wiyandikishije neza ✅",
  "registered alert message": "Ushobora kwinjira ubu!",
  "registration failed": "Kwiyandikisha vyanse ❌",
  head: "Umutwe",
  legs: "Amaguru",
  lips: "Iminwa",
  body: "Umubiri",
  eyes: "Amaso",
  fingers: "Intoki",
  "secret answer": "Inyishu ku gihimba",
  country: "Igihugu urimwo ubu",
  "insufficient engagement points": "Amanota (EP) ntahagije",
  "ep required to book message": "Ukeneye EP {minEpRequired} kugira ushoboze ku bookinga. Genda urabe ibigezweho!",
  "authentication error": "Ikosa ryo kwimenyekanisha",
  "wallet error": "Ikosa rya Wallet",
  "failed to fetch balance": "Vyanse kuraba amahera asigaye.",
  "insufficient balance": "Amahera ntahagije",
  "please add funds to wallet": "Shiramwo amahera muri wallet yawe.",
  "failed to verify wallet balance": "Vyanse gusuzuma amahera asigaye.",
  "invalid pin": "PIN siyo",
  "please enter 4-digit pin": "Injiza PIN y'ibiharuro 4.",
  "booking confirmed": "Ku bookinga vyakunze 🎉",
  "reserved seats message": "Wandikishije ibibanza {seatsLength} ku rugendo rwawe!",
  "booking failed": "Ku bookinga ntivyakunze",
  "something went wrong booking": "Hari ikibazo cabaye mu ku bookinga.",
  "not available": "Ntabihari",
  "seats": "Ibibanza",
  "seat price": "Igiciro c'ikibanza",
  "bus service fee": "Amahera ya seruvisi ya bus",
  "pay from gahungu wallet": "Riha na Gahungu Wallet",
  "checking eligibility": "Turiko turasuzuma ko ubirekuriwe...",
  "eligible to book message": "EP zawe ni {engagementPoints}, urashobora ku bookinga.",
  "ep less than required message": "EP zawe ni nke kuri {minEpRequired} zisabwa.",
  "earn ep by engaging": "Fyonda hano wongereko EP zawe mu kuraba inkuru, no kulikinga.",
  "enter pin": "Injiza PIN",
  "dashboardOverview": "Incamake ya Dashboard",
  "loadingStats": "Turiko turazana imibare...",
  "totalCustomers": "Abakiriya bose",
  "totalProducts": "Ibintu vyose",
  "totalRevenue": "Amafaranga yinjiye yose",
  "totalPendingOrders": "Ibitumye bitarashika",
  "totalViews": "Ababonye bose",
  "withdraw": "Kuraho",
  "withdrawSoon": "Team iriko irabikora, vuba birakora",
  "revenueLast7Days": "Amafaranga yinjiye (Iminsi 7 iheze)",
  "ordersLast7Days": "Ibitumye (Iminsi 7 iheze)",
  "profileViewsLast7Days": "Ababonye umwirondoro (Iminsi 7 iheze)",
  "recentActivity": "Ibikorwa biheruka",
  "orderId": "ID y'igitume",
  "noRecentOrders": "Nta bitumye biheruka",
  "welcomeGreeting": "Murakaza neza mwese",
  "welcomeGreetingSuffix": "kuri Platform ya Dr. Gahungu.",
  "myStock": "Stock yanje",
  "orders": "Ibitumye",
  "myPharmacy": "Pharmacie yanje",
  "getApprovedFirst": "Utegerezwa kubanza kwemererwa",
  "updatePasswordFail": "Kuhindura password vyanse",
  "updatePasswordSuccess": "Password yahinduwe neza",
  "underReview": "Turiko turasuzuma",
  "pendingStatusMessage": "Ubusabe bwawe buriko burasuzumwa na team yacu.",
  "approved": "Bwemejwe",
  "loadingForm": "Turiko turazana iforomaje...",
  "editResubmitApp": "Hindura kandi usubire urungike ubusabe",
  "stockManagement": "Uko ngenzura stock yanje",
  "editItem": "Hindura ikintu",
  "addNewItem": "Shiramwo ikintu gishasha",
  "itemName": "Izina ry'ikintu",
  "originalPrice": "Igiciro c'umwimerere",
  "quantity": "Igitigiri",
  "selectCategory": "Hitamwo category",
  "applicableInsurances": "Ubwishingizi bukwiranye",
  "uploadImage": "Shira hejuru ishusho",
  "changeImage": "Hindura ishusho",
  "updateItem": "Shira ku gihe ikintu",
  "addItem": "Shiramwo ikintu",
  "saving": "Turiko turabika...",
  "searchItemsPlaceholder": "Rondera ibintu...",
  "noItemsInStock": "Nta bintu biri muri stock",
  "noItemsMatchSearch": "Nta bintu bihuza n'ivyo uriko urondera",
  "inStock": "Bihari",
  "outOfStock": "Ntibihari",
  "incomingOrders": "Ibitumye bishasha",
  "customer": "Umukiriya",
  "viewItems": "Raba ibintu",
  "printInvoice": "Capa facture",
  "noBookingsFound": "Nta bitumye byabonetse",
  "openingHoursLabel": "Amasaha yo kwugurura",
  "hours24": "Amasaha 24",
  "payment summary": "Incamake y'ukuriha",
  "change PIN":"PIN niyo. Ubu urashobora kugira iyindi nshasha.",
  "pin mismatch":"PIN ntizisa. Subira ugerageze.",
  "failed to update pin":"Vyanse guhindura PIN. Raba ko ufise internet.",
  "pin must":"PIN itegerezwa kugira ibiharuro 4. Subira ugerageze.",
  "confirm update": "Emeza guhindura",
  "update profile logout message": "Guhindura umwirondoro wawe biraca bituma wideconnecta. Woba ushaka kubandanya?",
  "profile updated success message": "Umwirondoro wahinduwe neza! Ku bwo umutekano, ugir wideconecter. Cusubira winjire kandi.",
  "leave app facebook message": "Ugira usohoke muri app kugira uje Facebook. Woba ushaka kubandanya?",
  "leave app instagram message": "Ugira usohoke muri app kugira uje Instagram. Woba ushaka kubandanya?",
  "leave app twitter message": "Ugira usohoke muri app kugira uje kuri X. Woba ushaka kubandanya?",
  "missing order details": "Amakuru y'ivyo watumye ntiyuzuye.",
  "unexpected server response": "Server ntiyishuye neza.",
  "order failed": "Gutumwa vyanse",
  "failed create order": "Gutumwa vyanse. Subira ugerageze.",
  "payment failed": "Kuriha vyanse",
  "please try again": "Subira ugerageze.",
  "order placed message": "Commande yawe {orderId} yarungitswe!",
  "order details": "Ibikuru ku vyo watumye",
  "items": "Ibintu",
  "item": "Igikoresho",
  "sold by": "Vyagurishijwe na:",
  "status": "Aho bigeze:",
  "no items found": "Nta kintu na kimwe kiri muri iyi commande.",
  "order confirmation": "Kwemeza commande",
  "qr verification help": "Erekana iyi QR code muri pharmacie kugira basuzume.",
  "download invoice": "Kuraho Facture",
  "order not found": "Commande ntiyabonetse",
  "order details not found": "Amakuru y'ivyo watumye ntiyabonetse.",
  "wallet payment maintenance": "DR. IR. Gahungu ariko arabijengajenga, vuba birakora!",
  "create username": "Kora username",
  "update username": "Hindura username",
  "username hint": "Inyuguti 3-15, indome, ibiharuro, hamwe na underscore gusa.",
  "enter username": "Shiramwo username ushaka",
  "failed to update username": "Kuhindura username vyanse.",
  "add a comment": "Andika iciyumviro",
  "commenting as": "Uriko uratanga iciyumviro nka",
  "notifications": "Notifications",
  "no notifications yet": "Nta notifications zihari.",
  "mentioned you in a comment": "yakuvuze muri komantere",
  "replied to your comment": "yagishuye komantere yawe",
  "on post": "Kuri post",
  "create username title": "Kora username",
  "card maintenance": "Kuriha n'ikarata biriko birasanurwa.",
  "edit your application": "Hindura ubusabe bwawe",
  "welcome doctor application": "Murakaza neza muganga",
  "needs attention": "Ubusabe bwawe bukeneye kwitwararirwa",
  "rejection reason label": "Imvo zatumye vyankwa:",
  "rejection instructions": "Nyamuneka raba neza amakuru yawe, uhindure ibikenewe, uheze usubire urungike ubusabe bwawe.",
  "specialty": "Umwuga wawe",
  "country of origin": "Igihugu ukomokamo",
  "bio": "Bio",
  "bio placeholder": "Incamake y'ubuzima bwa muganga...",
  "payment id": "ID yo kuriha",
  "payment id placeholder": "ID yawe yo kuriha",
  "whatsapp hint doctor": "Tanguza kode y'igihugu nka +12345678",
  "password placeholder doctor": "Kora password",
  "doctor image": "Ishusho ya muganga",
  "choose image": "Hitamwo ishusho",
  "doctor terms": "Nemeye amategeko n'amabwirizwa ya Dr. Gahungu.",
  "resubmit form": "Subira urungike ubusabe",
  "submit form": "Rungika ubusabe",
  "application updated success": "Ubusabe bwahinduwe neza! Turaba turabusuzuma vuba.",
  "application submitted success": "Ubusabe bwarungitswe neza! Injira kugira urabe aho bigeze.",
  "submitting": "Turiko turarungika...",
  "passwordsMatchError": "Password nshasha ntizihuye",
  "incorrectCurrentPassword": "Password ukoresha ubu siyo",
  "enterCurrentPassword": "Shiramwo password ukoresha ubu",
  "passwordTooShort": "Password nshasha itegerezwa kugira inyuguti 6 canke zirenga",
  "updatePasswordError": "Habaye ikosa mu guhindura password",
  timesCommaSeparated: "Amasaha (atandukanijwe n'akarongo)",
  bookingType: "Uburyo bwo ku bookinga",
  onlineFee: "Amafaranga ya kuri internet",
  officeFee: "Amafaranga ya mu biro",
  remove: "Gufuta",
  day: "Umunsi",
  start: "Gutangura",
  end: "Guhera",
  breakStart: "Gutangura akaruhuko",
  breakEnd: "Guhera akaruhuko",
  inOffice: "Mu biro",
  both: "Vyose",
  fee: "Amafaranga",
}
};